### ISSUE TITLE
How does kubectl finds the latest replicaset of a deployment?

### ISSUE THREAD

**Issue by stavalfi** [kubernetes/kubectl#1022]
Is this a bug here?

this function is used to show the replicaset history of a deployment and to show the latest replicaset as the first one in the list:
https://github.com/kubernetes/kubectl/blob/aaaf1de578d4776237970e1e6faae41f3bb8993d/pkg/util/deployment/deployment.go
```
func findNewReplicaSet(deployment *appsv1.Deployment, rsList []*appsv1.ReplicaSet) *appsv1.ReplicaSet {
	sort.Sort(replicaSetsByCreationTimestamp(rsList))
	for i := range rsList {
		if equalIgnoreHash(&rsList[i].Spec.Template, &deployment.Spec.Template) {
			// In rare cases, such as after cluster upgrades, Deployment may end up with
			// having more than one new ReplicaSets that have the same template as its template,
			// see https://github.com/kubernetes/kubernetes/issues/40415
			// We deterministically choose the oldest new ReplicaSet.
			return rsList[i]
		}
	}
	// new ReplicaSet does not exist.
	return nil
}
```

I'm probably wrong but does findNewReplicaSet basically search for a replicateset with same image-name as the deployment (when comparing spec.templates, probably only the image-name will be different)? what if multiple replicatesets has the same image-name?

Why am I asking, I'm looking for a thread-safe way to search for the latest replicaset name of a deployment which I have in my hand. What can I do?

**Comment by eddiezane** [comment]
I was curious on the internals here and fell down the rabbit hole. Turns out ReplicaSets are actually reused if one matching the current Deployment PodSpec still exists (say you switch a deployment back to the previous image).

Check out this code from the deployment controller.

https://github.com/kubernetes/kubernetes/blob/9e5fcc49ec568f222a5274f443903d89fec3e591/pkg/controller/deployment/recreate.go#L29

https://github.com/kubernetes/kubernetes/blob/9e5fcc49ec568f222a5274f443903d89fec3e591/pkg/controller/deployment/sync.go#L110-L111 

Best to ask these types of questions on [Slack or the mailing list](https://github.com/kubernetes/community/tree/master/sig-cli#contact) in the future (we'd love to have you!).

/close
