### ISSUE TITLE
Error while executing bash script in pod location without exec in to pod via git bash

### ISSUE THREAD

**Issue by shanmukha511** [kubernetes/kubectl#1024]
**What happened**:
I am executing below command to execute shell script which is in pod location without exec in to pod but its trying to look the script in my local path not in pod path .

Command executing via git bash

kubectl exec -i pod-0 --namespace default -- bash /tmp/test.sh 

**Error Below:**

bash: C:/Users/testuser/AppData/Local/Temp/instance_restore.sh: No such file or directory
command terminated with exit code 127

**What you expected to happen**:

It should execute the script from pod location using the above command.

**How to reproduce it (as minimally and precisely as possible)**:

Run a pod and place a script inside the pod and execute below command getting error 127 exit code.

kubectl exec -i pod-0 --namespace default -- bash /tmp/test.sh 

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:31:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
google cloud
- OS (e.g: `cat /etc/os-release`):

**Comment by eddiezane** [comment]
Your versions a pretty out of support. Please upgrade your client and try again.

https://kubernetes.io/docs/setup/release/version-skew-policy/

/close

**Comment by Wolfium** [comment]
While it was closed by old version unsupported the root cause as can see is because git_bash in windows has some weird issues handling slash starting path to handle unix posix like path and windows local paths

It is related to `/tmp/test.sh` part of your command being processed as local path by git bash.
There are 2 ways to handle it

If it just call (not part of any script to be share) you can escape the first slash using double slash, 
changing original 
`kubectl exec -i pod-0 --namespace default -- bash /tmp/test.sh`
to this
`kubectl exec -i pod-0 --namespace default -- bash //tmp/test.sh`
will work like a charm

If you want to get git bash to work more close to a linux bash using an exported environment variable to disable this POSIX PATH CONVERSION at the beginning will allow you to use a single slash not escaped like any linux OS.
Be aware when posix path conversion is disabled you will lose the way to exec any binary with the linux path style, ie: `notepad /tmp/myfile.txt` will not work any more
`export MSYS_NO_PATHCONV=1`

Hope it helps in clarifying the original issue which is not related to kubectl, it happens with any binary call with a file path within parameters.
