### ISSUE TITLE
Can't read certificate authority from named pipe

### ISSUE THREAD

**Issue by aeriksson** [kubernetes/kubectl#1025]
It seems that kubectl can't read `--certificate-authority` from named pipes or `/dev/stdin`.

**What happened**:
```bash
$ cat ~/.kube/config | grep certificate-authority | head -n 1 | sed 's/.* //' | base64 --decode > cluster.ca

$ kubectl --certificate-authority=cluster.ca get pods
No resources found in default namespace.

$ kubectl --certificate-authority=<(cat cluster.ca) get pods
Unable to connect to the server: x509: certificate signed by unknown authority

$ cat cluster.ca | kubectl --certificate-authority=/dev/stdin get pods
Unable to connect to the server: x509: certificate signed by unknown authority
```

**What you expected to happen**:
This should work regardless of whether kubectl is reading from a regular file, from a named pipe, or from `/dev/stdin`.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
Kubectl seems to handle this properly for `--kubeconfig`, so presumably there's some difference between how it's reading `--certificate-authority` and `--kubeconfig`. Perhaps it's trying to read the CA file twice? It gives the same error if passed an empty file.

**Environment**:
Tested on macOS with kubectl 1.20.4 and Debian 10 with kubectl 1.18.16.

**Comment by lauchokyip** [comment]
@dougsland  I can take a look at this one :)

**Comment by dougsland** [comment]
> @dougsland I can take a look at this one :)

hey @lauchokyip sure thing, thanks!

**Comment by lauchokyip** [comment]
Hi @aeriksson , I am sorry I am not able to reproduce the errors.
When I did `cat ~/.kube/config | grep certificate-authority | head -n 1 | sed 's/.* //' ` the output is not base64 decoded so it can't be decoded. 
Any idea how to reproduce it @aeriksson  and @dougsland ? Thank You

**Comment by aeriksson** [comment]
@lauchokyip for local setups (like with Minikube), you'll typically have a ca file referred via the `certificate-authority` key, but for cloud-based/production setups you'll normally have a Base64-encoded cert under `certificate-authority-data`. See https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

**Comment by lauchokyip** [comment]
@eddiezane , did some diggings

**Comment by lauchokyip** [comment]
Every time we set up a DiscoveryClient, we will have to [set up a new REST client](https://github.com/kubernetes/kubernetes/blob/268cab5f444531d11a63d06872bf850c65f814fe/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L233), therefore we will have to set up the TLS connection again, that's why it's showing errors given the fact that `/dev/fd/63` can only be read once

**Comment by lauchokyip** [comment]
https://github.com/kubernetes/kubernetes/pull/97855 , related issue

**Comment by lauchokyip** [comment]
@eddiezane , @soltysh , @KnVerey  even doing it with fixed client wouldn't work because it will be copy to [transport config](https://github.com/kubernetes/kubernetes/blob/268cab5f444531d11a63d06872bf850c65f814fe/staging/src/k8s.io/client-go/rest/transport.go#L63) and the client does not have `CAData` to begin with in the first place. 

Any thoughts? 🤔
