### ISSUE TITLE
config get-contexts and custom-columns output

### ISSUE THREAD

**Issue by socketbox** [kubernetes/kubectl#1052]
**What would you like to be added**:

I would like `kubectl config get-contexts` to show an arbitrary subset of the columns shown in default output by way of the `-o=custom-columns` flag.

**Why is this needed**:
Currently, `kubectl config get-contexts` shows CURRENT NAME CLUSTER AUTHINFO and NAMESPACE. On my terminal, that's a total of 221 columns, with NAME, CLUSTER, and AUTHINFO being _identical_ for all contexts.

`kubectl config get-contexts` documentation shows only one output option: `-o=name`. Attempts to override this with `-o=custom-columns="CURRENT:.metadata.current,NAME:.metadata.name"` (for example) result in an error.

**Comment by eddiezane** [comment]
My guess is that custom columns were added to `kubectl get` at a later point and never ported to config.

We would accept a PR if reusing the [custom columns from kubectl get](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/get/customcolumn.go) is clean otherwise the maintainer burden probably outweighs the benefit.

In the meantime take a look at [kubectx](https://github.com/ahmetb/kubectx). It's what I use to switch clusters.

/triage accepted
/priority backlog

**Comment by lauchokyip** [comment]
will try to tackle this one

**Comment by lauchokyip** [comment]
@eddiezane , I don't think there will be a clean solution because in order to use the custom column printer it needs to take in a [decoder](https://github.com/kubernetes/kubernetes/blob/7696a48612c1ae7bd1a39dcb0004804cf2ebb6fd/staging/src/k8s.io/kubectl/pkg/cmd/get/customcolumn.go#L72). Right now the `get_context.go` is [hard coded](https://github.com/kubernetes/kubectl/blob/5f7f2be39326e1bc341f01d1014e7659283b2b76/pkg/cmd/config/get_contexts.go#L167) to just five columns, which are all `strings`. (I think )To make the custom column works, instead of just [reading from ConfigAccess](https://github.com/kubernetes/kubectl/blob/5f7f2be39326e1bc341f01d1014e7659283b2b76/pkg/cmd/config/get_contexts.go#L64), we might have read in the whole config file, convert it to json , and make a new [`PrintObj`](https://github.com/kubernetes/kubernetes/blob/7696a48612c1ae7bd1a39dcb0004804cf2ebb6fd/staging/src/k8s.io/kubectl/pkg/cmd/get/customcolumn.go#L157) function
