### ISSUE TITLE
kubectl delete -n <namespace> with --all causes deletion of all resources in all namespaces without providing --all-namespaces or -A

### ISSUE THREAD

**Issue by abhiTamrakar** [kubernetes/kubectl#1056]
**What happened**: 
Someone with admin access could accidentally provided --all switch to delete one namespace and it caused cluster-wide deletion of all namespaces and their objects.

`kubectl delete namespace -n <namespace>` with --all causes deletion of all resources in all namespaces without providing --all-namespaces or -A

**What you expected to happen**: Deletion of just one mentioned resource or all resources under one namespace should happen

**How to reproduce it (as minimally and precisely as possible)**:

Please Run to reproduce (***I know this is already known but still for anyone reading it, kindly do not run on a live cluster***):
`kubectl delete namespace -n <namespace> --all`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 1.19.9
- Cloud provider or hardware configuration: NA
- OS (e.g: `cat /etc/os-release`): CentOS7

**Comment by eddiezane** [comment]
Hi @abhiTamrakar - this is the expected behavior here.

When a namespace is deleted it also [deletes all of the resources in it](https://kubernetes.io/docs/tasks/administer-cluster/namespaces/#deleting-a-namespace). By running `kubectl delete namespace --all` you will be deleting every namespace and all of the resources in them (except for the system namespaces - you should have seen errors that they can't be deleted).

The `-n <namespace>` you are providing is a bit quirky here. It normally would scope the request to the provided namespace - `kubectl -n foo delete pods --all` would delete all of the Pods in the `foo` namespace. In the case of working with namespaces as a resource itself it doesn't have an effect.

If you wanted to delete an individual namespace you could use `kubectl delete namespace <namespace>`.

I do think we need to think through some of these footgun scenarios a bit more. We haven't really been able to because changes like asking for confirmation would break existing scripts. See https://github.com/kubernetes/kubectl/issues/921.

/triage support
/close

**Comment by abhiTamrakar** [comment]
@eddiezane as the conversation is continued on slack https://kubernetes.slack.com/archives/C2GL57FJ4/p1621573084002200
This is definitely a bug, either in documentation of these flags or the way they are currently implemented.
