### ISSUE TITLE
Kubectl should not describe all APIs when executing unrelated calls

### ISSUE THREAD

**Issue by ellistarn** [kubernetes/kubectl#1077]
**What would you like to be added**:
Kubectl currently describes all APIs before executing a simple command like `kubectl get pods`. Instead of doing this in all cases, it should only describe APIs when dealing with objects that it does not recognize (e.g. pessimistic vs optimistic describing). 

I'm trying to think of why the current behavior could be necessary. The only thing that occurs to me is that kubectl might need to handle overlapping shortnames (i.e., if a CR used a shortname `pods`). It's not clear to me what the behavior of kubectl should be at that point. My sense is that overlapping short names should be validated at CRD creation time. Minimally, kubectl should prioritize core resources over CRDs in the overlapping case.

**Why is this needed**:
When users install many custom resources (e.g. 180, in my case), this can result in significantly increased latency for every kubectl. There doesn't appear to be any workaround when using kubectl in this scenario, other than removing the CRDs.

**Comment by ellistarn** [comment]
It's also not clear to me why the .kube/cache/discovery is not mitigating this latency.

**Comment by ellistarn** [comment]
> It's also not clear to me why the .kube/cache/discovery is not mitigating this latency.

Ah -- I appear to not have write permissions to this. With this resolved, latencies are gone. This seems like an acceptable solution to me :)

**Comment by shyamjvs** [comment]
@ellistarn Can you reopen the issue to get an answer for our question on why kubectl needs to make discovery calls for well-known object types?

**Comment by eddiezane** [comment]
> Ah -- I appear to not have write permissions to this.

We log this at `-v 1`. Not sure if exposing that at base level was ever discussed. Might just confuse folks. We also continue on with discovery after a write failure because the API still needs to be walked but we might be able to abort writing to speed up.

> why kubectl needs to make discovery calls for well-known object types?

The API server is the source of truth. Well-known object types don't really exist to the client. The client needs to talk to past and future versions of the API server with different APIs at different stages so discovery is relied on.

That said there are probably optimizations to make as CRD usage and count increases.

> When users install many custom resources (e.g. 180, in my case), this can result in significantly increased latency for every kubectl.

I don't think every CRD is walked during discovery but someone else might need to explain what is chosen and why. You can test his yourself by using the cache writing failure :).

```
kubectl get pods --cache-dir /var/nowrite -v 1
```

ref: https://github.com/kubernetes/kubernetes/issues/102378 for priority
