### ISSUE TITLE
Custom columns option breaks when using spaces

### ISSUE THREAD

**Issue by ampc** [kubernetes/kubectl#1088]
**What happened**:
I was trying to get some custom output and when I inserted a space after comma, it returned an error.

**What you expected to happen**:
Display a syntax error instead of not found error

**How to reproduce it (as minimally and precisely as possible)**:
Error (notice the space after comma and before **DEPLOYMENT2**)
```bash
root@controlplane:~# kubectl get deployments --namespace admin2406 -o custom-columns=DEPLOYMENT:.metadata.name, DEPLOYMENT2:.metadata.name
Error from server (NotFound): deployments.apps "DEPLOYMENT2:.metadata.name" not found
``` 
No space after comma
```bash
root@controlplane:~# kubectl get deployments --namespace admin2406 -o custom-columns=DEPLOYMENT:.metadata.name,DEPLOYMENT2:.metadata.name
DEPLOYMENT   DEPLOYMENT2
deploy1      deploy1
deploy2      deploy2
deploy3      deploy3
deploy4      deploy4
deploy5      deploy5
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): v1.19.0
- Cloud provider or hardware configuration: Digital Ocean
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04

**Comment by eddiezane** [comment]
Cheers @ampc,

This is how most cli's parse arguments.

Because there was a space it took the next string as the arg for the deployment name. Hence the error of `deployments.apps "DEPLOYMENT2:.metadata.name" not found`.

You can avoid this by wrapping the flag value in quotes but it will take the space as the first character of the second column. We could trim that but I'm not sure it buys us much.

Is there a need to have a space between columns?

```
 kubectl get deployments -o custom-columns="DEPLOYMENT:.metadata.name, DEPLOYMENT2:.metadata.name"
DEPLOYMENT    DEPLOYMENT2
pihole       pihole
```

**Comment by ampc** [comment]
Hi @eddiezane,

No, there isn't a specific need for this. It was more like something I usually do (adding spaces after commas).

**Comment by eddiezane** [comment]
> Hi @eddiezane,
> 
> No, there isn't a specific need for this. It was more like something I usually do (adding spaces after commas).

Roger. Going to close this then.

/close
