### ISSUE TITLE
"kubectl describe <resource>" doesn't take into account the new fields of core.v1/event

### ISSUE THREAD

**Issue by dsonck92** [kubernetes/kubectl#1095]
When trying to implement sending Events from a controller, I decided to adhere to the new Event structure from core.v1. This has the notable changes that the `count` value and `lastTimestamp` are now deprecated in favor of `series.count` and `series.lastObservedTime`.

However, when using these fields, when invoking `kubectl describe deployment app1`, only `eventTime` is considered for the `Age` column.

When executing `kubectl get event <event-name>`, the `LAST SEEN` column is giving the right value and properly updates.

Expected behavior:

When executing `kubectl describe <resource> <name>`, the correct `lastObservedTime` and `count` should be shown.

**Comment by dsonck92** [comment]
Soo, it might be a bit more nuanced. Apparently while implementing the said Event data, I completely missed the fact that there are 3 different types, one from `events.k8s.io/v1beta1`, one from `events.k8s.io/v1` and one from `core/v1`.

`core/v1` seems to include both the fields from `events.k8s.io/v1beta1` and `events.k8s.io/v1` without the `deprecated` renaming from `v1`, however one thing that strikes me as odd is that (as said earlier) `kubectl get events` does show the correct data from `series` and `kubectl describe <event-target>` doesn't. But from what I understand, I should be using `core/v1` instead since it matches in fields to what kubernetes is giving back.

**Comment by eddiezane** [comment]
/triage accepted
/help

This is potentially a good first issue but we'll need to document the work needed.

**Comment by lauchokyip** [comment]
@rikatz , you wanna take a look at this one?

**Comment by lauchokyip** [comment]
@eddiezane , @rikatz  is looking for some good-first-issues to mentor other people so I am looking out for him

**Comment by harjas27** [comment]
Hi, I would like to work on this issue. I looked into the code and it seems like this is where the issue lies:
https://github.com/kubernetes/kubectl/blob/864f10512dd6931254e8af5a7f0b95de7bdfa8f7/pkg/describe/describe.go#L4144
there would be an update to use the newer fields `EventSeries.Count` and `EventSeries.LastObservedTime`

**Comment by eddiezane** [comment]
/assign @harjas27 

Thanks! Let us know if you need help and take me on the PR please.

**Comment by KnVerey** [comment]
A clarification on the background here: there are 3 version of Event. The original is `core/v1`, and the latest is `events.k8s.io/v1` (which also has a corresponding beta). Since the original is used as the storage version / for backwards compatibility, it was enhanced with many of the new fields as well. The related KEP is tracked here: https://github.com/kubernetes/enhancements/issues/383. It includes [a useful table](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md#backward-compatibility) on the various fields across versions. 

This is what `describe` displays:
* Type: same in all versions
* Reason: same in all versions
* From: `e.Source.Component` in core.Event and `e.ReportingController` in events.Event. The corev1.Event type we're using has both fields. This is already accounted for in the current describe code.
* Message: `e.Message` in core.Event and `e.Note` in events.Event, but it would seem [conversion](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/events/v1/conversion.go#L39) takes care of this one--the corev1.Event type we're using only has the former.
* Age: the problem this issue is highlighting. In core.Event, we have `e.FirstTimestamp`, `e.LastTimestamp` and `e.Count`. In the beta events.Event API, we have the same prefixed with "Deprecated", but those are taken care of by conversion and don't appear in the corev1.Event type we're using. In both the beta and the GA events.Event API, we also have `e.EventTime`, `e.Series.LastObservedTime` and `e.Series.Count`. All six non-deprecated fields appear in the corev1.Event type we're using. As far as I can tell, it's perfectly possible for either or even both to be populated, and there is not automatic conversion between them. I was unable to dig up guidance on how clients should handle them, but my instinct is to treat them as two sets, one of which is given priority when present, and to avoid combining data across the sets (e.g. always use e.Series.Count instead of e.Count when displaying e.Series.LastObservedTime).

With that research out of the way, I'll review the PR shortly. 😅

**Comment by dsonck92** [comment]
That table (and info in general) would have been so useful while I was playing about with doing the event generation. I was pretty confused about the state events were in which cost a few hours.

From some personal experience, (and briefly going through the info), it seems like Series should be used if available, and the old fields as fallback since a lot of kubernetes internal controllers still use the old fields. For now, I've solved it for myself by populating both fields while using the core.v1 api, but as I learn just now, I should eventually move over to the events api. But I'll deal with that once the kubernetes java library forces me, or when this is properly handled by kubectl which was essentially my main idea for emitting events in the first place (finding out what my controller is doing while not parsing logs)
