### ISSUE TITLE
kubectl explain <resource>: show valid mappings for fields of type map[string]string

### ISSUE THREAD

**Issue by MoBoo** [kubernetes/kubectl#1104]
**What would you like to be added**:
Add a list of possible resource keywords to the `kubectl explain` output for fields of type `map[string]string` to give an overview of possible mapping options.
This could look something like the existing `FIELDS:` section and would also be beneficial for the official documentation.
For example:
`kubectl explain pv.spec.capacity` would also show a list of possible mappings like:
```
KEYS:
storage: <short desc>
```

**Why is this needed**:
While it is possible to get a good explaination of a resource like `pv.spec.capacity.storage` it is **not** possible to get an overview over which keywords exist (for example) under the `pv.spec.capacity` field. (`kubectl explain pv.spec.capacity`)

Currently it is hard for beginners to get a easy overview of possible `yaml` definitions. For simplicity reasons it would be beneficial if the `kubectl explaim` command would show a list of available mappings for fields of type `map[string]string` like its done for the fields of an `Object` like `pv.spec`.

Further this might also be beneficial for the offical documentation, because for example in the current documentation of the `persistent volumes capacity` ([here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#capacity)), there is no mention that the `storage` keyword exists, but it is even mentioned as "Currently, storage size is the only resource that can be set or requested" which would one to think the keyword would be `storageSize` or similar. 
This is also true for many other fields of type `map[string]string`.

**Comment by soltysh** [comment]
This was discussed in length during yesterday's sig-cli bug scrub (you can watch it here: https://youtu.be/P-e2jzsc1FE) and we've agreed that we can reliably present the information about keys in the map in this particular case. In this particular case you're describing the type definition looks [[like so](https://github.com/kubernetes/kubernetes/blob/a48a2efbd45ad77901dd09f2665d8cc1e1d8dbf6/staging/src/k8s.io/api/core/v1/types.go#L331):
```golang
Capacity ResourceList
```
and we can't extract possible values from `ResourceList` because that can have one of four values, see https://github.com/kubernetes/kubernetes/blob/a48a2efbd45ad77901dd09f2665d8cc1e1d8dbf6/staging/src/k8s.io/api/core/v1/types.go#L4992-L5002. But the validation code for this field explicitly allows only `storage` there (see https://github.com/kubernetes/kubernetes/blob/a48a2efbd45ad77901dd09f2665d8cc1e1d8dbf6/pkg/apis/core/validation/validation.go#L1719). That additional information is explicitly printed in the fields description with a link pointing to docs explaining that field in details, which is sufficient. 

/close

**Comment by xorinzor** [comment]
@soltysh I'm aware this is an old issue, but I just ran into this and found this issue, but found your explanation a bit confusing.

At first you say:
> we've agreed that we can reliably present the information about keys in the map in this particular case. 

But go on to say:
> we can't extract possible values from ResourceList because that can have one of four values

In an example question I was asked to get all `PersistentVolumes` and sort them by `capacity`.
`kubectl explain pv --recursive=true` only shows the `.spec.capacity` field (without nested fields), and `kubectl explain pv.spec.capacity` only talks about the `Quantity` field.

As it turns out, the field you're supposed to use is: `.spec.capacity.storage`.

Neither the output from `explain`, nor the [linked documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#capacity) that it mentions, provide any context around this `storage` field.

As a beginner I haven't been able to figure out the solution to this question and had to look up the answer.

Is there any way the documentation on this can be improved? If one of 4 values can possibly be returned, perhaps these 4 values should be also some kind of `type` that can be referenced to within the documentation, and can be referenced to by using `kubectl explain <type>`.

Not only in day-to-day use (especially while learning), but also during practical exams, having this documentation available without going online is important.
