### ISSUE TITLE
bash completions stop working when aliasing `kubectl --kubeconfig` on v1.22

### ISSUE THREAD

**Issue by josefschabasser** [kubernetes/kubectl#1119]
**What happened**: bash completions stop working when aliasing `kubectl --kubeconfig` on v1.22. We work with multiple clusters and use an activation script to prepare working environments and quickly switch between them. Kubeconfig files are recreated upon activation using `azure-cli` to keep the users home directory clean and refresh access tokens.
```bash
$ alias kubectl='kubectl --kubeconfig=/path/to/kubeconfig'
$ kubectl des<TAB> ==> kubectl describe
$ kubectl describe pods<TAB> ==> <nothing happens>
```
In zsh everything is fine:
```zsh
$ alias kubectl='kubectl --kubeconfig=/path/to/kubeconfig'
$ kubectl des<TAB> ==> kubectl describe
$ kubectl describe pods<TAB> ==> <gives choice: pods, pods.metrics.k8s.io, pods, podsecuritypolicies.policy>
```
![grafik](https://user-images.githubusercontent.com/45227795/133971959-e35fe66a-d053-4efc-a0b2-e2af70272f78.png)

**What you expected to happen**: bash completions work as they do in 1.21.x

**How to reproduce it (as minimally and precisely as possible)**:
1. open bash
2. move your kubeconfig to a temporary location: `mv ~/.kube/config ~/kubeconfig`
3. try autocompletion: `kubectl --kubeconfig=kubeconfig describe pods<TAB>` - works
4. alias kubectl: `alias kubectl='kubectl --kubeconfig=kubeconfig'`
5. try autocompletion: `kubectl describe pods<TAB>` - doesn't work
6. move kubeconfig back:  `mv ~/kubeconfig ~/.kube/config`

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): server: 1.22.1, client: 1.22.1/1.22.2
- Cloud provider or hardware configuration: Azure Kubernetes Services
- OS (e.g: `cat /etc/os-release`): Manjaro Linux (x86_64, GNOME)

**Comment by marckhouzam** [comment]
I can reproduce the problem and I believe its related to #1116 where `kubectl` tries to look for a plugin before performing the `__complete` command, but the --kubeconfig flag makes the plugin logic abort.  I will continue digging.

**Comment by marckhouzam** [comment]
Ok so here's what's happening.  When doing
```
$ alias kubectl='kubectl --kubeconfig=/path/to/kubeconfig'
$ kubectl des<TAB> ==> kubectl describe
$ kubectl describe pods <TAB> ==> <nothing happens>
```
The first completion is a static completion of the command `describe`.  This is hard-coded in the bash completion script and is not affected by the bug.

The second completion is a custom completion; it needs to call the cluster to know what the list of pods is.  For custom completions, now that we use Go custom completions (since https://github.com/kubernetes/kubernetes/pull/96087) the bash script will call:
```
kubectl __complete describe pods ''
```
but because of the alias, this gets replaced with
```
kubectl --kubeconfig=/path/to/kubeconfig __complete describe pods ''
```
and because of bug #1116, `kubectl` will look for a plugin for the `__complete` command, and plugins don't allow flags that follow `kubectl` immediately.  So the custom completions break.

For `zsh` we are lucky.  `zsh` replaces the alias *before* calling the completion script, so the command 
```
$ kubectl describe pods <TAB>
```
gets replaced with
```
kubectl --kubeconfig=/path/to/kubeconfig describe pods <TAB>
```
which then causes the completion script to call
```
kubectl __complete --kubeconfig=/path/to/kubeconfig describe pods ''
```
and although `kubectl` will still look for a plugin, the `--kubeconfig` flag is no longer placed right after `kubectl` and things work.

I will improve https://github.com/kubernetes/kubernetes/pull/105141 which tries to fix #1116 to properly handle this case, which I had not considered.

**Comment by lauchokyip** [comment]
Thanks for the details explanation!

/triage accepted
/priority important-soon
/assign @marckhouzam

**Comment by marckhouzam** [comment]
@josefschabasser https://github.com/kubernetes/kubernetes/pull/105141 should address your issue.

**Comment by josefschabasser** [comment]
@marckhouzam Does this also fix completion for resource definitions, like `kubectl get p<TAB>` which should give me this list:
```
persistentvolumeclaims
persistentvolumes
poddisruptionbudgets.policy
pods
podsecuritypolicies.policy
pods.metrics.k8s.io
podtemplates
priorityclasses.scheduling.k8s.io
prioritylevelconfigurations.flowcontrol.apiserver.k8s.io
```
