### ISSUE TITLE
Support for reading `--namespace` and `--context` values from env vars

### ISSUE THREAD

**Issue by danielhoherd** [kubernetes/kubectl#1154]
**What would you like to be added**: Please add support for reading `--namespace` and `--context` values from env vars.

**Why is this needed**: Currently users have the ability to read the value of `--kubeconfig` from the `KUBECONFIG` env var. This is quite useful when working in different terminals with different config files, especially given that the settings are scoped not only to the current shell and its children, but to the lifecycle of that shell process. IE: when the shell exits, the configurations used in that shell do not persist. My workflow uses this mechanic to make sure I never open a new shell into a config that has production access.

However, when working with different namespaces and contexts in different terminals, if you do not want to work within the namespace or context of what is contained in the on-disk configuration, every command must include `--namespace=this` or `--context=that`. Without the ability to inherit these properties from the environment, users are required to either type them out long form or write wrapper functions or aliases.

I think the important feature here is the ability to configure the client environment within the lifecycle of the current PID, without persisting those configurations to disk. This is important from a parallel operation standpoint, and from the standpoint of starting new PIDS with a known configuration state.

**Comment by eddiezane** [comment]
@danielhoherd @mpuckett159 we discussed this today on our call. Please take a listen when you get a chance and let us know your thoughts on the concerns raised.

https://youtu.be/qb1z2MKROvw?t=2838

**Comment by danielhoherd** [comment]
@eddiezane thanks for including a link to the recording. It's great to see the conversation you all and and the care you took in discussing it, suggesting alternatives and potential pitfalls.

To summarize what I took from the conversation, it sounds like the risks and uncertainty of having one more place to configure namespace and context are leading you all in the direction of not implementing this feature.

I think that is a reasonable stance to take. While I do not agree with it, it is an acceptable decision. The original request I made was essentially a convenience request, not a new feature, and given that there are already options available I'm not going to press it further.

**Comment by mpuckett159** [comment]
I appreciate the time y'all took to discuss and explain.

I'll admit, though, I didn't really put much thought into the "why" of the PR. I just saw it, thought "oh I know how to do this" then did it. Appreciate the deeper considerations brought up.

I think after hearing the discussion I agree that default namespace settings should exist within the context (heh) of the context that is set. To that end, switching namespaces should be held within the switching of a context, and the kubeconfig file should have the appropriate context's configured with the appropriate namespaces that are desired. So I think we can drop that part.

For contexts, I think the points around safety and visibility brought up are important. There isn't a default way to display the current context and namespace settings for a user. You can see in the PR I made that I attempted to accomplish this by adding some warning lines when a setting was done via environment variable, but at that point it's too little too late anyway so it's kind of moot. The only way to handle this is, as mentioned, configuring your terminal to read and output these settings for you, or implementing a confirmation prompt a la `terraform apply`. That being said, I don't think this change would increase the problem beyond the scope it already has.

It seems like a potential issue that someone could set this env var in their profile config (.bashrc, .zshrc, etc.), such that they wouldn't necessarily know that the variable is configured when they open a new terminal. I can see how that would be problematic and should probably be advised against if this gets implemented. Could possibly implement a command to explain where settings are being derived from in the current shell? That may be hopelessly difficult, though, or at the very least require a pretty heavy lift since today (from what I saw) the source of these settings isn't really considered and the values are just pulled in a specific order, so we would have to add a new object to track that, or update the config object.

Really, though, I do think the context setting via env var makes sense. As the original issue states, currently there isn't a way to set a shell contained context, and it makes total sense to me that someone would want to temporarly set a context within their session that would not persist beyond that session without having to remember to run `kubectl config use-context <context>` at the end of their session, especially in the case outlined above, but also in the case that a user has multiple shells open that could potentially be working in different contexts. Using `kubectl config use-context <context>` could possibly break that set up if they're using the same kubeconfig for all their shells.

Since `use-context` will persist beyond the life of the shell, I think it makes sense to provide a way to temporarily set the context, and because we can't really update the file "on shell close" I'm not sure how that would work outside this solution. Adding a `kubectl config use-context <context>` to the shell profile file would present other issues as well, as mentioned above.

Sorry this ended up being a lot longer than I thought it would be.

**Comment by danielhoherd** [comment]
Since @mpuckett159 chimed in with a great analysis of his view of the problem, I'll piggy back on that and point out a few comparisons. Hierarchical configuration resolving is not a new concept. See [hiera](https://puppet.com/docs/puppet/7/hiera.html), [Ansible](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable), [pxe](https://wiki.syslinux.org/wiki/index.php?title=PXELINUX), [CircleCI](https://circleci.com/docs/2.0/env-vars/#order-of-precedence), [GitlabCI](https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence), [`$PATH`](https://www.ibm.com/docs/en/aix/7.1?topic=accounts-path-environment-variable), [environment.d](https://man7.org/linux/man-pages/man5/environment.d.5.html), [k8s pod env](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core), and on and on. So the problem of a user trying to manage where config options come from is IMHO par for the course when using k8s. IMHO there shouldn't be any issues for a unix command to inherit configurations from the environment, and quite the opposite I think env vars should be a first class citizen from day 1. Environment variables are something system operators and engineers should have a firm understanding of and fluency with. They are a [fundamental component of posix](https://pubs.opengroup.org/onlinepubs/9699919799/), and by extension of cloud services and devops.

**Comment by eddiezane** [comment]
Thanks for the continued thoughts! I've spoken with a few others about this since.

For some context, [client-go](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go) is where loading kubeconfigs and other env vars comes from. Most Kubernetes tooling (built in Go) uses client-go in some way.

https://github.com/kubernetes/kubernetes/blob/5426da8f69c1d5fa99814526c1878aeb99b2456e/staging/src/k8s.io/client-go/tools/clientcmd/loader.go#L42

https://github.com/kubernetes/kubernetes/blob/5426da8f69c1d5fa99814526c1878aeb99b2456e/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go#L584

Implementing this change solely in kubectl would introduce inconsistency to the ecosystem. A change like this would need to be added to client-go so other Kubernetes tooling could pick it up as well. And this is where we've run into issues in the past when trying to implement things like the [XDG config specification or something like `.kubeconfig.d/`](https://github.com/kubernetes/kubectl/issues/1123#issuecomment-1005958599) for holding multiple configs. Unless other tools pull in the client-go changes and ship a new version, and users update (the hard part here) there will be functionality difference between which cluster each tool is operating on.

Due to the impact on the ecosystem this would need to land as a [KEP](https://github.com/kubernetes/enhancements).

So this isn't a "no" but we haven't found a good way to make these types of changes.

**Comment by eddiezane** [comment]
Closing this to clear our queue.

@danielhoherd btw we'd love to have you join us if solving things like this interests you! https://github.com/kubernetes/community/tree/master/sig-cli#meetings

/close

**Comment by ei-grad** [comment]
For those who came across this issue through search results, here's a helpful approach for working with multiple contexts, especially if you're using `direnv`. You can find the original suggestion in [this comment](https://github.com/kubernetes/kubernetes/issues/27308#issuecomment-309207951):

> @chancez The following alias addresses the need for default settings:
> 
> ```bash
> alias k='kubectl "--context=${KUBECTL_CONTEXT:-$(kubectl config current-context)}" ${KUBECTL_NAMESPACE/[[:alnum:]-]*/--namespace=${KUBECTL_NAMESPACE}}"'
> ```
> 
> - It works in both bash and zsh.
> - Supports shell auto-completion.
> - Does not break auto-completion, as discussed in the following issue:
>   - [Kubectl bash completion doesn't properly handle namespace flag #29322](https://github.com/kubernetes/kubernetes/issues/29322)
> 
> When combined with `direnv`, which sets shell environment variables based on the current location in the file system, this solution allows you to work in parallel on different clusters in different shells, depending on the project folder you are in.

Additionally, I suggest using the `KUBE_CTX` variable, which has been [adopted](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#config_context) by the `kubernetes` Terraform provider.

**Comment by H-repos** [comment]
For those who are always working with different contexts in different terminals,here is https://github.com/H-repos/kuber-plus

**Comment by meteozond** [comment]
I wonder how many clusters will be destroyed before it gets implemented.
