### ISSUE TITLE
kubectl autocompletion does not work when using --context flag with a context that contains a colon

### ISSUE THREAD

**Issue by frederik-b** [kubernetes/kubectl#1157]
**What happened**:

tab autocompletion does not work when explicitly declaring the context

**What you expected to happen**:

tab autocompletion does work when explicitly declaring the context

**How to reproduce it (as minimally and precisely as possible)**:
does work for me:
```
kubectl --namespace=test get pods <tab> <tab>
kubectl --namespace test get pods <tab> <tab>
```

does not work for me:
```
kubectl --context=arn:aws:eks:eu-central-1:1234567890:cluster/foo-bar --namespace=test get pods 
kubectl --context arn:aws:eks:eu-central-1:1234567890:cluster/foo-bar --namespace=test get pods 
```

**Anything else we need to know?**:
I found: https://github.com/kubernetes/kubectl/issues/1119
and thought it might fix it, but if I understand correctly this is included in v1.23.0 (not sure though)
and this is still not working

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): client: v1.23.0, server: 1.20.7-eks-d88609 (and others)
- Cloud provider or hardware configuration: tested with aws, gcp, rancher2
- OS (e.g: `cat /etc/os-release`): Fedora Linux 35
- Shell: bash 5.1.8(1)-release

**Comment by marckhouzam** [comment]
This is a regression with v1.22 when `kubectl` moved to using Go completions 😞 

The problem is with the `:` that are part of your context @frederik-b.  The bash completion script provided by Cobra that `kubectl` uses does not handle the `:` properly in every case (https://github.com/spf13/cobra/issues/1355#issuecomment-787222293).

However, I believe that if you quote your context it will work.  You could try something like this:
```
kubectl --context 'arn:aws:eks:eu-central-1:1234567890:cluster/foo-bar' --namespace=test get pods <tab> <tab>
``` 

As for a permanent fix, we would either need to fix Cobra, or `kubectl` would need to move to using Cobra's [bash completion V2](https://github.com/spf13/cobra/blob/master/shell_completions.md#bash-completion-v2) which does not have this problem.

**Comment by marckhouzam** [comment]
> This is a regression with v1.22 when `kubectl` moved to using Go completions 😞

Actually, I was wrong, the bug is present, but it is not a regression.  The same problem happens with kubectl 1.21.8 which had not yet moved to Go completions.

**Comment by frederik-b** [comment]
After a little bit more testing it does only work when using equal signs and not when using spaces.
I rewrote my daily use alias which now looks as follows.
```
alias kubectl='kubectl ${KUBECTL_CONTEXT:+--context=$KUBECTL_CONTEXT} ${KUBECTL_NAMESPACE:+--namespace=$KUBECTL_NAMESPACE}'
```
and today it worked even with that aws arn:aws:eks stuff with all the colons

I believe my first test case was wrong (only namespace without equal sign).
Still on 1.23.0
So it's probably fixed already?

I would like to understand why the alias only works with the `=` while it does otherwise work with the space syntax.

also a function apparently works the same as an alias

**Comment by brianpursley** [comment]
> As for a permanent fix, we would either need to fix Cobra, or `kubectl` would need to move to using Cobra's [bash completion V2](https://github.com/spf13/cobra/blob/master/shell_completions.md#bash-completion-v2) which does not have this problem.

You're right about what is happening regarding cobra's completion function considering `:` to be a word delimiter.

I confirmed that `GenBashCompletionV2` as you mentioned appears to fix the problem and completions seem to still work fine.  

@marckhouzam Is there any reason you know of that it would not be a good idea to move to V2?

It should be a very simple fix on our end.

In the meantime, anyone who needs to use a context name that has a colon can either quote it, like `--context="foo:bar"` or can escape the colon like `--context=foo\:bar`.

**Comment by brianpursley** [comment]
> I would like to understand why the alias only works with the = while it does otherwise work with the space syntax.

@frederik-b Your observation is correct, that completions work when an alias contains `-n=foo`, but do not work when an alias contains `-n foo`

This is a known issue an also [affects plugin invocations as well](https://github.com/kubernetes/kubectl/issues/884#issuecomment-646278462).

The cause is in this code, where it interprets the first word not starting with a `-` to be a command name, not a value for a flag.  `-n=foo` works because it is considered a single word.  `-n foo` is considered two words by this code.

https://github.com/kubernetes/kubernetes/blob/c4fbd35cf4bdc76b86dd74e468b69328f5aa20f9/staging/src/k8s.io/kubectl/pkg/cmd/cmd.go#L121-L127

I know it may not be immediately clear what this has to do with completions, but under the hood.

When a completion is requested for `kubectl -n foo get pod <TAB>`, under the hood, the bash completion script invokes:
```
kubectl __completeNoDesc -n foo get pod  ""
```

In this case, `__completeNoDesc` is the first non-flag word, and everything works as expected.

However if you have an alias like:
```
alias k=`kubectl -n foo`
complete -F __start_kubectl k
```

And then if you do `k get pod <TAB>`, under the hood, the bash completion script invokes:
```
k2 __completeNoDesc get pod  ""
```

But the alias expands to:
```
kubectl -n foo __completeNoDesc get pod  ""
```

Now kubectl sees `foo` as the first non flag and thinks it is a plugin.

In fact, if you invoke this command you can see the error that occurs, which is hidden when the completion call is made:
```
~ $ kubectl -n foo __completeNoDesc get pod  ""
Error: flags cannot be placed before plugin name: -n
```

So, while I realize this is not ideal, it is an explanation of what is happening and why you have to use `=` when specifying flag values inside an alias.

**Comment by marckhouzam** [comment]
> @marckhouzam Is there any reason you know of that it would not be a good idea to move to V2?

@brianpursley Bash completion v2 has a couple of benefits beyond this bug fix, but you should be aware of them to know exactly what the changes implies:

1. Support for descriptions like zsh and fish (and PowerShell).  You must opt-in to this feature and could allow your users to disable it (as helm does)
1. It only recommends `--flag` instead of both `--flag=` and `--flag` which is better for the user
1. The completion script has a fixed and small size, less than 300 lines, compared to kubectl's current 14K lines script.
1. Aligned behaviour with zsh and fish.
1. Support for completions which includes a `=` or `:`

If you wish to enable descriptions of completion choices kubectl should first move to Cobra 1.3 to get this fix: https://github.com/spf13/cobra/pull/1509

Helm has been using the bash completion v2 in the wild for 4 months (helm 3.7.0) and the only bug report was for this fix that's part of Cobra 1.3.  Podman has been using it for even longer than that.

**Comment by brianpursley** [comment]
/retitle kubectl autocompletion does not work when using --context flag with a context that contains a colon

**Comment by brianpursley** [comment]
@marckhouzam Thanks for the info!  I'll take a look at upgrading Cobra to 1.3 and turning on descriptions too.  We might as well take advantage of the descriptions if we can, since it would be available with V2 completions.
