### ISSUE TITLE
kubectl-convert does not handle custom resources

### ISSUE THREAD

**Issue by vnhirenko** [kubernetes/kubectl#1187]
**What happened**:
We use kustomize to deploy our service and would like to utilize kubectl-convert to handle api version conversion.
We custom resources in kustomization stack for example, we have Istio RequestAuthentication manifest.

when we try to run `kubectl-convert -k . --local=false` it returns:

`unable to decode ".": no kind "RequestAuthentication" is registered for version "security.istio.io/v1beta1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"`

**What you expected to happen**:
conversion should skip custom resources which it does not able to convert

**How to reproduce it (as minimally and precisely as possible)**:
run kubectl-convert with any k8s custom resource

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): client: v1.21.0, Server: v1.21.5
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`): Ubuntu 21.10

**Comment by eddiezane** [comment]
kubectl-convert relies on internal types of the Kubernetes project and will not support CRDs as a generic implementation is not feasible.

/triage unresolved
/close

**Comment by brannondorsey** [comment]
I think @vnhirenko's ask is a reasonable one.

> **What you expected to happen**:
conversion should skip custom resources which it does not able to convert

I too would like to see the output of resources which _can_ be converted, and warn on the ones that can't, rather than failing completely.

I recognize that CRDs won't be implemented and that's fine. But it is impossible to see the output of `kubectl convert` on any kustomize project which uses even 1 CRD, even if there are 100 other standard K8s resources which could be converted.
