### ISSUE TITLE
Use "Contains" when completing kubernetes contexts

### ISSUE THREAD

**Issue by eachirei** [kubernetes/kubectl#1196]
**What would you like to be added**: Use Contains instead of HasPrefix in ListContextsInConfig function for autocomplete.

**Why is this needed**: Having contexts which start with various prefixes based on the cloud provider, it would be useful to search for contexts containing a string.

**Comment by seans3** [comment]
None of the autocompletion uses `Contains`, so we will not pursue this to keep consistency with other autocompletions--closing.

/close

**Comment by marckhouzam** [comment]
I was planning on eventually suggesting to completly remove the `HasPrefix()` checks for the auto complete logic.  Kubectl should return all possible completions and let the shell decide how to do the matching.  Zsh and Fish both have smarter matching algorithms than the simple prefix match.

The completion scripts are ready for such an approach and helm has started taking advantage of it (https://github.com/helm/helm/pull/10513). 

I find it very useful for completing namespaces because in my case we use common prefixes to group namespaces but I don't always remember which group the workload I'm looking for belongs to.

I can post a PR soon to get feedback.
