### ISSUE TITLE
kubectl wait allow to wait on missing field

### ISSUE THREAD

**Issue by jduepmeier** [kubernetes/kubectl#1204]
**What would you like to be added**:

Add a flag to signal that a field in jsonpath should not error if the field or object in chain does not exist.

**Why is this needed**:

I want to wait for a specific field in the status of a resources inside a script with the following command:

```
kubectl wait  --for=jsonpath=.status.ready=true
```

But the status field does not exist on creation of the resource. This can result in a race condition if the controller does not add the field fast enough. If the field does not exist the wait command will error.

It would be nice if the wait command can wait on fields which will be created later on the resource.

**Comment by soltysh** [comment]
/triage needs-information

Before deciding if we want to accept this I'd like to ensure we can differentiate between 2 diametrically different situations:
1. when the field is not set (ie. has `omitempty` so it won't show up, but it exists in schema)
2. when the field does not exist, ie. was misspelled. 

If we can differentiate, then I can definitely support option no. 1, since that will bring the value asked in the original comment. If we can't I'd prefer we error out.

**Comment by jduepmeier** [comment]
In my case i want to wait on  the kyverno clusterpolicy crd (https://htmlpreview.github.io/?https://github.com/kyverno/kyverno/blob/main/docs/crd/v1/index.html#kyverno.io/v1.ClusterPolicy)

It defines `status` as optional.

**Comment by mpuckett159** [comment]
/close

I believe this is resolved by #109525. Please reopen if it is not actually resolved.
