### ISSUE TITLE
Completion for set-context --current --namespace

### ISSUE THREAD

**Issue by abrekhov** [kubernetes/kubectl#1215]
**What would you like to be added**:
`kubectl config set-context --current --namespace`  autocompletion for bash and zsh. 

**Why is this needed**:

I am using zsh with oh-my-zsh wrapper. It will be wonderful to quickly select namespace by "tabbing" through all of them.

**Comment by marckhouzam** [comment]
@abrekhov because the `kubectl config set-context` re-uses the word `--namespace` for one of its flag and shadows the global `--namespace` flag, you can actually use the existing shell completion logic for your case, just put the flag before the `config` command.

```
$ kubectl config --namespace <TAB>
# or
$ kubectl --namespace <TAB>
# and then
$ kubectl --namespace myns config set-context --current
Context "lab" modified.
```
So the completion happens for the global flag, but then will work for your case as well.

This is not a good final solution, but it can prove useful to you until a full solution is maybe implemented.

**Comment by mpuckett159** [comment]
Looks like this has been satisfactorily answered, thank you Marc.

/close
