### ISSUE TITLE
kubectl all vs --all

### ISSUE THREAD

**Issue by AydinChavez** [kubernetes/kubectl#1235]
**What would you like to be added**:

For retrieving and describing all objects we use an action:
```
kubectl get all ..
kubectl describe all ..
```

For deleting objects we use a flag:
`kubectl delete --all ..`

Proposal always use "all" instead of "--all"
```
kubectl get all ..
kubectl delete all ..
```

**Why is this needed**:
Simplify working with kubectl.

**Comment by brianpursley** [comment]
I know it seems like `kubectl get all` is a special command that gets all resources, but it is actually not.

"all" is just a category name that is advertised by some set of resource types (pods, rc, services, ds, deployments, ss, hpa, cronjobs, and jobs).

What's going on under the hood is `all` is being resolved to match a category specified by some set of resource types.

For example, daemonset:
https://github.com/kubernetes/kubernetes/blob/80060a502c3f86f00800fbeba7684a85f1ce5e17/pkg/registry/apps/daemonset/storage/storage.go#L77-L79

The unfortunate part is that the category should never really probably have been called "all" because there is no way to make sure that all resources advertise themselves as belonging to that category.  So it is nearly impossible for it to really be all.

A bit of trivia: There is another category defined called "api-extensions" so similarly, you can run `kubectl get api-extensions` and it will return things, even though there is no "api-extensions" resource type.  It works the same way as `kubectl get all`

**Comment by eddiezane** [comment]
As Brian pointed out `all` is something that we would do completely differently if we started from scratch. We are slowly trying to remove the concept of it but cannot for backwards compatibility promises.

/close
