### ISSUE TITLE
`error: open .kube/config.lock: permission denied`

### ISSUE THREAD

**Issue by samuel-mellert** [kubernetes/kubectl#1246]
**What happened**:
I'm running `kubectl` inside of a docker container. 
The user's `.kube` folder is mounted from the host system via volume mount.
Since I'm running macOS I'm using [virtiofs](https://www.docker.com/blog/speed-boost-achievement-unlocked-on-docker-desktop-4-6-for-mac/).
When running `kubectl config use-context {context-name}` I get this error message:
`error: open /home/user/.kube/config.lock: permission denied`

In the `.kube/` directory there's now a file `config.lock` with `chmod 0`:
`----------    1 user     user             0 Jul 22 07:25 config.lock`

**What you expected to happen**:
The `.kube/config` file gets modified and the `current-context:` is saved.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This does NOT happen when using the regular host filesystem mounts, only in combination with virtiofs.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by samuel-mellert** [comment]
I admit that this issue is pretty specific for a setup that's probably not too common atm, however it was curious enough so I wanted to leave some sort of documentation.

I'm currently using a workaround using `sed` to replace the `current-context:` line inside of the `config` file.
This works for me as long as the file format doesn't change, but maybe there's an easy fix for this issue.

**Comment by Jonnymcc** [comment]
This issue affects us. The setup is going to become more common because in [Docker for Mac 4.21.0](https://docs.docker.com/desktop/release-notes/#4210) VirtioFS is now the default. I saw somewhere that VirtioFS doesn't support remote file locking and I'm guessing it is related. What alternatives are there to removing the lock file implementation altogether?

**Comment by mike-potter** [comment]
Not sure how to get progress on this.  We are also running into this issue and it's preventing us from using VirtioFS with Docker Desktop.  But not sure if this is really something Kubernetes needs to fix, or if it's an issue that VirtioFS and Docker Desktop need to fix.

One of our users is testing OrbStack instead of Docker Desktop and even though OrbStack also uses VirtioFS it doesn't seem to have this problem with Kubernetes.

**Comment by holiday-sunrise** [comment]
This issue affects us.
