### ISSUE TITLE
kubectl diff failed when creating the namespace and resources at the same time

### ISSUE THREAD

**Issue by koba1t** [kubernetes/kubectl#1331]
### What happened?

kubectl diff failed when creating the namespace and resources in the new namespace at one YAML file with multiple documents. 
kubectl shows the below error.

```sh
Error from server (NotFound): namespaces "new-namespace" not found
```

### What did you expect to happen?

Show message to create new namespace and resources.

### How can we reproduce it (as minimally and precisely as possible)?

Exec to `kubectl diff` for the below YAML file.

```sh
$ kubectl diff -f new-pod.yaml
```

```yaml
# new-pod.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: new-namespace
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: example
  name: example
  namespace: new-namespace
spec:
  containers:
  - image: nginx:latest
    name: example
  restartPolicy: Never
```

### Anything else we need to know?

I tried to fix this issue, but I didn't decide how to fix it. I write my thinking to the below list.
- handle `namespace not found` error at [this line on diff.go](https://github.com/kubernetes/kubectl/blob/cf0626ffbf4e4f8e9a7abaf557c69b8761b0b34b/pkg/cmd/diff/diff.go#L566).
  - It needs kubectl saves `create namespace` history on the series of diff commands to memory.
  - I think this way is hard to check the effect to create real resources because I think any effects are happening on the k8s clusters like admission webhooks.
- actual create namespaces for kube-apiserver during exec diff command and delete those namespaces after `kubectl diff` finishing.
  - I think this way affects the cluster and maybe happen a few problems, in the case of kubectl exec on parallel or sigkill happening while exec kubectl diff.

### Kubernetes version

<details>

```console
$ k version --short
Client Version: v1.25.4                                                                                                                                                                                            Kustomize Version: v4.5.7                                                                                                                                                                                          
Server Version: v1.23.5  
```

</details>

### Cloud provider

<details>
baremetal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ardaguclu** [comment]
Thanks for the issue @koba1t 

This is the same behavior of `kubectl apply --dry-run=server`. kubectl sends to api server one resource at a time and api server can not know that user has an intention to create namespace prior to this resource. That's why, it returns an error. 

> handle namespace not found error at [this line on diff.go](https://github.com/kubernetes/kubectl/blob/cf0626ffbf4e4f8e9a7abaf557c69b8761b0b34b/pkg/cmd/diff/diff.go#L566).
It needs kubectl saves create namespace history on the series of diff commands to memory.
I think this way is hard to check the effect to create real resources because I think any effects are happening on the k8s clusters like admission webhooks.

Saving namespace history in kubectl does not fix the problem. Because everything is happening at api server. How can we ensure that diff output is correct after discarding the response of api server?

> actual create namespaces for kube-apiserver during exec diff command and delete those namespaces after kubectl diff finishing.
I think this way affects the cluster and maybe happen a few problems, in the case of kubectl exec on parallel or sigkill happening while exec kubectl diff.

Diff is not allowed to create anything in cluster. Because creating something has an impact on cluster. What about the edge cases like you are trying to create namespace already existed and diff decides to delete it after executing difference?. Wouldn't that bring a lot of complexity.

I think, supporting this kind of complexity breaks the simplicity of flow which we don't want and brings about several edge cases. Asking user to create dependent resources before `diff` or `apply --dry-run=server` looks to me simpler.

I'd prefer closing this issue.

**Comment by ardaguclu** [comment]
@apelisse @seans3 what is your opinion about this problem?

**Comment by apelisse** [comment]
Yeah, this is hard, I have no clue how we can fix this properly, not without very complicated machinery.

**Comment by apelisse** [comment]
That's working as intentded, sorry.
/close

**Comment by Amitabh1989** [comment]
```
C:\GitHub\01-hello-world-rest-api>kubectl diff -f deployment.yaml
The Service "kubernetes" is invalid:
* metadata.uid: Invalid value: "d77215bb-86c7-40b8-b505-d039a6365897": field is immutable
* spec.clusterIPs[0]: Invalid value: []string{"10.60.0.1"}: may not change once set
```

Am I also seeing the same issue? I keep getting this error when I dump the deployment.yaml file, change the image tag and issue a diff command.

**Comment by apelisse** [comment]
Well, you seem to have a service in that `deployment.yaml` that you're trying to update in a way that makes the apiserver unhappy.

**Comment by jeremiahbowen** [comment]
Two options here:
```
if ! kubectl get namespace newrelic &> /dev/null; then
    echo "Namespace 'newrelic' not found. Creating for first run..."
    kubectl create namespace newrelic
fi
(
    kubectl diff -f manifest.yaml || result=$?; result="${result:-$?}"
    [[ $result -eq 1 ]] || && echo "diff exited with $result; skipping" || exit "$result"
)
```
Or what I think is worse because it will hide other exit 2 errors.
```
(
    kubectl diff -f manifest.yaml || result=$?; result="${result:-$?}"
    [[ $result -eq 1 ]] || [[ $result -eq 2 ]] && echo "diff exited with $result; skipping" || exit "$result"
)
```
These assume you're using set -e in your script but will work regardless. The subshell is so the result isn't carried further into your script for the next time you use it. ` || exit "$result"` is reached for exit 0 or any other value that isn't skipped.
