### ISSUE TITLE
kubectl cp: "Unexpected EOF" / kubectl exec fails to read entire buffer

### ISSUE THREAD

**Issue by DamianFekete** [kubernetes/kubectl#1361]
**What happened**:
`kubectl cp pod:/tmp/500MB 500MB` fails to transfer the entire file. 
The last 10-40MB are not transferred.

**What you expected to happen**:
The file (500MB) is transferred completely and correctly.

**How to reproduce it (as minimally and precisely as possible)**:
To debug this I've used `kubectl exec` with a redirection instead of `kubectl cp`.

```shell
# This doesn't work (for me), it transfers only about 170MB. Runs for 50-60 seconds.
# I can see in a parallel console that after the bash process terminates, kubectl still runs for about 10-12 seconds.
kubectl bash -c "(dd if=/dev/zero bs=1MB count=200)" > output-200

# This works correctly.
# After sleep and bash terminate, kubectl terminates promptly. 
# The file has the expected size.
kubectl bash -c "(dd if=/dev/zero bs=1MB count=200; sleep 15s)" > output-200
```

**Anything else we need to know?**:
From my laptop I can achieve a download speed of about 4 to 7 MB/s from the K8s cluster.
I've tested the speed during the transfer using `pv`.

My assumption is that some buffers are getting full (as the download speed is limited), and either kubectl is notified that the process ended and doesn't wait for the transfer to complete or Linux closes the connection after some timeout.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
  * Client Version: v1.25.4
  * Kustomize Version: v4.5.7
  * Server Version: v1.24.8-dhc
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): `Windows 10` (client), `Ubuntu 20.04.1 LTS` (pod)

Probably related to https://github.com/kubernetes/kubectl/issues/1103

**Comment by igor0** [comment]
I put together a standalone repro and pointed to the likely root cause in the discussion here:
* https://github.com/kubernetes/kubernetes/issues/60140#issuecomment-1364264111
* https://github.com/kubernetes/kubernetes/issues/60140#issuecomment-1364369348
* https://github.com/kubernetes/kubernetes/issues/60140#issuecomment-1364566417

It's possible that the existing issue ([60140](https://github.com/kubernetes/kubernetes/issues/60140)) mixes reports of multiple unrelated problems related to `kubectl cp` and so perhaps a standalone issue just for the EOF problem makes sense.

**Comment by brianpursley** [comment]
Let's track this on the other issue
https://github.com/kubernetes/kubernetes/issues/60140#issuecomment-1363456588

/close
