### ISSUE TITLE
Improvements around kubectl delete --all

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [kubernetes/kubectl#1365]
### What would you like to be added?

`kubectl delete --all pods -n yournamespace` will delete all pods in a namespace.

Likewise

`kubectl delete --all pvc -n yournamespace` will delete all volume claims in a namespace.

BUT...

`kubectl delete --all pv -n yournamespace` generally means you are going to be spending the next few hours restoring from backups. 

I recommend either....

1. Asking a warning confirmation if you are sure you want to delete all of your PVs... or
2. Detecting the -n parameter, and throwing an error for invalid arguements

### Why is this needed?

Since, uh, PVs aren't scoped to a namespace, before you can break out of the command...... you have deleted all of your PVs.

Well, since k8s does not have a good method of "undeleting" objects, this might at least save someone else a bit of time restoring backups.

Knock on wood, in my specific case- I have working backups, AND.... my PVs appear to just hang around stuck in a deleting state forever... even with no attachments.

**Comment by ardaguclu** [comment]
I agree that this is a problem. I think we can add a validation to not allowing `--namespace` and cluster-wide resource at the same time and warn user about `--namespace can only be used for namespaced resources`, etc. That at least prevents this.

In terms of backwards compatibility, people should already use `kubectl delete --all pv` instead `kubectl delete --all pv -n namespace`.

**Comment by ardaguclu** [comment]
We have already a warning in here https://github.com/kubernetes/kubernetes/blob/75ff830ab198348b0c727d05e54754d5f73a7286/staging/src/k8s.io/kubectl/pkg/cmd/delete/delete.go#L318. @XtremeOwnageDotCom did you see that warning?(although it does not interrupt process)

**Comment by ardaguclu** [comment]
@XtremeOwnageDotCom  I added this issue in sig-cli meetings agenda which will be happening today.

**Comment by XtremeOwnageDotCom** [comment]
> Ah, this reminds me of `rm -rf /`, I think users need to be responsible for what they do.

Normally- I would agree fully with you-

The issue I am throwing here-

`kubectl delete --all pv -n your.namespace` is not a valid command, because PersistentVolumes are NOT namespaced. -n / --namespace isn't even a valid parameter when used with pv. 

However, if there was an error displayed at all, it would have been AFTER it flagged all of your PVs as `Terminating`

My reason for this request wasn't to limit the power of this command- but, at a minimum- to make the invalid parameters at least throw an error, instead of having a user mistype pv, instead of pvc, leading to complete and utter destruction.

**Comment by ardaguclu** [comment]
We discussed this at sig-cli meeting and decided that this is expected behavior as stated in here https://github.com/kubernetes/kubectl/issues/1056#issuecomment-847415661.

In the future, kuberc and interactive delete(proposed in here https://github.com/kubernetes/kubernetes/pull/114530) are planned to solve that problem.

Since currently we need to wait referenced PRs and Kuberc KEP are implemented and merged, I'm going to close this issue as duplicate of https://github.com/kubernetes/kubectl/issues/1056.

Feel free re-open it if you think I'm missing something.

/close

**Comment by fotto1** [comment]
@XtremeOwnageDotCom can you reopen the issue?

I would really recommend to follow comment https://github.com/kubernetes/kubectl/issues/1365#issuecomment-1422560977

An interactive mode for deletion like described under https://github.com/kubernetes/kubernetes/pull/114530 will not solve that problem. If you not use the flag you still run in the issue, I also expect an error message after the option `-n` is not available see https://github.com/kubernetes/kubectl/issues/1413

**Comment by delvh** [comment]
I agree with previous commenters that the current state is borderline dangerous:

> Ah, this reminds me of rm -rf /, I think users need to be responsible for what they do.

Yes, but that's a different pretense:
Everyone knows that `/` is the filesystem root.
However, when you pass `-n`, you do not expect that something that isn't even in this namespace is deleted.
And there are at least two reasons why this can happen:
- Accidental mistyping as described above
- Not knowing that pvs are not namespaced (which is why I'm adding my two cents - after all, the `-n` parameter is still offered and accepted, so I'd guess they are ) 
My definition of "responsibility" is not `pretend to be a breeze but turn out to be a hurricane`.
And after all, there is a reason why `rm` had to add an extra option `--no-preserve-root`.
They needed to prevent users from shooting themselves in the foot like that. 

I do not think declaring that when `-n` is present it is intended behavior that everything is deleted.
This action is too disruptive for that to happen.
I can accept `get` or similar simply printing a warning, but `delete` should never be possible with an unexpected value.
