### ISSUE TITLE
bash completion not working when kubectl is aliased with kubeconfig

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes/kubectl#1367]
**What happened**:
This looks like a extreme case and minor issue. But I wanted to file this anyway to get some opinions about it.

```sh
$ mv /home/user/.kube/config /home/user/.kube/test_config
$ alias kubectl='./_output/bin/kubectl --kubeconfig=/home/user/.kube/test_config'
$ kubectl get namespaces <tab>
completion works without any problem

$ alias kubectl='./_output/bin/kubectl --kubeconfig /home/user/.kube/test_config'
$ kubectl get namespaces <tab>
completion does not work
```

The only difference between two aliases is `--kubeconfig=/home/user/.kube/test_config'` vs `--kubeconfig /home/user/.kube/test_config'`

**What you expected to happen**:
I'd expect that completion works when kubectl is alised with `--kubeconfig test_config`.

**Anything else we need to know?**:
as stated in this case https://github.com/kubernetes/kubectl/issues/1181#issuecomment-1058078922, it is very likely that this is Cobra issue.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.0-alpha.1.353+70dde8d746a073-dirty", GitCommit:"70dde8d746a07392d945dde32dd7e3b12ca9a043", GitTreeState:"dirty", BuildDate:"2023-02-10T13:56:18Z", GoVersion:"go1.20", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Kind cluster
- OS (e.g: `cat /etc/os-release`):
Fedora 37

**Comment by ardaguclu** [comment]
@marckhouzam would you mind giving some insights on this?. Probably there is nothing we can do but I'll close this issue after verifying that problem is known. Thanks.

**Comment by marckhouzam** [comment]
I can reproduce the problem.  

You can get more details by doing the underline completion command:
```
./_output/bin/kubectl --kubeconfig /home/user/.kube/test_config __complete ''
Error: flags cannot be placed before plugin name: --kubeconfig
```
This has to do with how plugins are detected and the fact that we don't try to figure out if an argument belongs to the preceding flag or is a new argument.  The logic that fails in this case is here:
https://github.com/kubernetes/kubectl/blob/c230e1b22140e5767a57860f8d1ca3669859565d/pkg/cmd/cmd.go#L119-L139

What happens:
1. line 119 does not find a existing command because it is the yet-to-be-created `__complete` command
2. the loop at line 124 only ignores arguments starting with a `-`, so it wrongly thinks the `cmdName` is `/home/user/.kube/test_config`, which is not a known command, so it looks like a plugin
3. the `HandlePluginCommand()` gets called, and it fails because you are not allowed to specify a flag (in this case `kubeconfig` before a plugin command.

I feel like we've seen this before and just agreed that in this rare case, the = form of the flag should be used.

**Comment by ardaguclu** [comment]
@marckhouzam many thanks for investigating this. I'm going to close this hoping that if someone in the future navigated this issue due to same problem can find the solution in your explanation.

/close
