### ISSUE TITLE
kubectl autoscale: Add `--mem-percent` option

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubectl#1374]
**What would you like to be added**:

CPU usage is one of major keys for HPA, and we can specify the target average CPU utilization as `--cpu-percent` option.
Memory usage also is one of them, and it is useful to support specifying the target utilization as `--mem-percent` option. 

**Why is this needed**:

We can create the HPA instance of the target memory utilization from YAML file now.
However it is useful to create the instance with `kubectl` command line because we don't need to maintain the YAML file on user side.

**Comment by mpuckett159** [comment]
/close
autoscale is an imperative command, and at present the direction of kubectl is to provide imperative commands as learning tools for users, which necessitates a reduction in the number of required flags to facilitate that learning by not over whelming the user. For more advanced use cases (such as described in this issue) we would advise that users should be using the declarative tools to accomplish these tasks.

**Comment by oomichi** [comment]
@mpuckett159 
Thank you for your comment.
Could you help me understand current direction of kubectl?

> at present the direction of kubectl

Do you have any links about the above direction like KEPs, issues or slack discussion?

> the declarative tools

What kind of tools is impled here? kustomize or something?

**Comment by mpuckett159** [comment]
Declarative would be the apply command, which can be used in conjunction with kustomize yes.

Here are some sources for you regarding this direction and the differences between the tools:

- [Kubernetes Object Management](https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/) - this has a few more links within it for further details
- [Presentation by SIG lead Katrina Verey from KubeCon NA 2022](https://youtu.be/BDZFtYUnmCw?t=488) - In this video (starting from the 8:08 timestamp) Katrina explains more about the differences between imperative vs declarative object management, the how and why, and she also explains some of the reasoning behind why production systems should not be used for production management. She also details why we highly recommend the use of apply and declarative object management instead of imperative object management. This presentation has been given a few times I believe, this is the most recent I'm aware of.

**Comment by oomichi** [comment]
@mpuckett159 Thank you so much for your advice!
That helps me much :-)
