### ISSUE TITLE
"error: unexpected EOF" when following logs

### ISSUE THREAD

**Issue by msw1996** [kubernetes/kubectl#1391]
What happened:
After approx 10 mins, following a log bails out with "error: unexpected EOF". The pod is not generating output during this time, so feels like the log follow gives up if its not receiving data often enough.

What you expected to happen:
Logs should be followed indefinitely, even if the pod has quiet periods.

How to reproduce it (as minimally and precisely as possible):
kubectl logs <podname> -f

**Comment by msw1996** [comment]
the same quetion as https://github.com/kubernetes/kubectl/issues/595

**Comment by ardaguclu** [comment]
@msw1996 thanks for raising this issue. 

As far as I can see kubelet flag `streaming-connection-idle-timeout` determines the timeout value of idle connection and in your case this might be set to 10 minutes(default is 4 hours). More context can be found in these issues https://github.com/kubernetes/kubernetes/issues/104580, https://github.com/kubernetes/kubernetes/issues/104595.

It might not work but it is worth to pass `--ignore-errors` flag to `kubectl logs`(as suggested in here https://github.com/kubernetes/kubectl/issues/1313). 

I'm closing this issue, since there seems to be no bug related to kubectl. Feel free to re-open it, if you think I'm missing something.

/close
