### ISSUE TITLE
Failure to Create Pod with Fractional Gi Resource Requests/Limits

### ISSUE THREAD

**Issue by kevarr** [kubernetes/kubectl#1426]
**What happened**:

When applying a Pod manifest with a memory request/limit value of 1.1Gi the value is changed when applied to the server and the following warning is thrown:

```shell
Warning: spec.containers[0].resources.requests[memory]: fractional byte value "1181116006400m" is invalid, must be an integer
```

**What you expected to happen**:

Server side pod resource request/limits match what was supplied in the client side manifest.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
kubectl create -f - << EOF
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-pod
      image: busybox
      command: ["sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      resources:
        requests:
          cpu: 250m
          memory: 1.1Gi
        limits:
          cpu: 250m
          memory: 1.2Gi
EOF
```

**Anything else we need to know?**:

Related: https://github.com/kubernetes/kubectl/issues/1250

**Environment**:
- Client Version: v1.26.1
- Server Version: v1.26.1
- Cloud provider or hardware configuration: minikube v1.29.0, also reproduced on AWS EKS 1.24
- OS: MacOS Ventura Version 13.3.1

**Comment by mpuckett159** [comment]
/close

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory

Above is a link to the docs that explains in more detail how the conversion from GiB to B works and why you are receiving this error. To summarize, 1.1GiB converts to 1181116006.4 B (or 1181116006400 mB). I recommend that you use the 1.1G notation instead of Gi, unless you truly do want 1181116006.4 B of memory assigned to your container. In that case, the warning is valid, however it should still create the container for you.
