### ISSUE TITLE
kubectl should accept --to-revision option

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes/kubectl#1428]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

I want to patch an annotation of an older revision of a deployment

**What you expected to happen**:

I want to use this command to patch it

kubectl patch deployment mydeployment --patch '{"metadata": {"annotations": {"kubernetes.io/change-cause": "custom message"}}}' --namespace mynamespace --record=false
--to-revision 3

**How to reproduce it (as minimally and precisely as possible)**:

There is nothing to reproduce

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: all-version

**Comment by pierluigilenoci** [comment]
@helayoty, any news about this?

**Comment by pierluigilenoci** [comment]
@rikatz @helayoty @lauchokyip, any feedback about this?

**Comment by liggitt** [comment]
> I want to patch an annotation of an older revision of a deployment

This data is pulled from the `kubernetes.io/change-cause` annotations in the replicasets for the deployment ... if you want to modify the change reason for one of them, you can patch the replicaset object directly.

I don't think it makes sense to add type-specific logic into a generic command like patch.

**Comment by brianpursley** [comment]
Yeah, I don't see `kubectl patch` getting a deployment-specific flag, but you can accomplish what you want using existing functionality in bash, like this:
```
kubectl patch replicaset "$(kubectl get replicasets -o jsonpath='{range .items[*]}{.metadata.ownerReferences[0].name}{" "}{.metadata.annotations.deployment\.kubernetes\.io/revision}{" "}{.metadata.name}{"\n"}{end}' | awk '$1 == "foo" && $2 == "2" {print $3}')" --patch '{"metadata": {"annotations": {"kubernetes.io/change-cause": "'"My Change Reason"'"}}}'
```

The above command gets the replicaset name for revision "2" of deployment "foo", and then patches the change cause to be "My Change Reason".

You might be able to simplify this somehow, but it shows how it can be done.

I'm going to close this issue, since there is a way to do this using existing functionality.
