### ISSUE TITLE
Unusable Secret manifest for type docker-registry

### ISSUE THREAD

**Issue by danielmilanov** [kubernetes/kubectl#1439]
Running:

`kubectl create secret docker-registry <NAME> --from-file=<path/to/.docker/config.json>`

will create a Secret with `.data` value of `config.json`.

Kube-apiserver will reject such a secret with:

`The Secret "NAME" is invalid: data[.dockerconfigjson]: Required value`

Running:
```
kubectl create secret generic <NAME> \
    --from-file=.dockerconfigjson=<path/to/.docker/config.json> \
    --type=kubernetes.io/dockerconfigjson
```
however will output a manifest with acceptable `.data` value of `.dockerconfigjson`.

Intended use is exactly the same, so behaviour should probably be consistent.

`Client Version: v1.24.0`

TIA

**Comment by ashutosh887** [comment]
Should I work on this @danielmilanov 

Please assign

**Comment by mpuckett159** [comment]
/triage accepted
If someone would like to take this on it will be required to be backwards compatible to ensure users who are expecting the existing command structure will not be broken. Therefore it will need to support both:
`kubectl create secret docker-registry <NAME> --from-file=<path/to/.docker/config.json>`
and
`kubectl create secret docker-registry <NAME> --from-file=.dockerconfigjson=<path/to/.docker/config.json>`

The reason that this is working the way it is currently appears to be because the create secret subcommands make use of a handful of generic functions that need the key type passed along in the `--from-file` flag, however the subcommands don't fill that information in for the user and expect it to be supplied in the flag, though it should be automatically supplied by the subcommand.
