### ISSUE TITLE
Support create job --from job/<job_name> to create Job from suspended job

### ISSUE THREAD

**Issue by alexef** [kubernetes/kubectl#1441]
**What would you like to be added**:

At the moment, only [cronjobs are supported](https://github.com/kubernetes/kubectl/blob/a5b0052b8993ed982e8df8c97de7abc4263b3967/pkg/cmd/create/create_job.go#L260).

**Why is this needed**:
We would like to be able to run:
```
kubectl create job <newname> --from job/<existing_suspended_job>
```
and trigger a job from a suspended job.

**Comment by mpuckett159** [comment]
/close
Due to the limited nature and scope of the imperative commands (create, replace, delete) and their intention to be learning tools, we only have a limited set of objects that are able to be created using them. Please read further [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/).
