### ISSUE TITLE
kubectl run command doesn't honor `Ctrl+C` when used with `sleep`

### ISSUE THREAD

**Issue by harshanarayana** [kubernetes/kubectl#1445]
**What happened**:
When using `kubectl run` in interactive mode with `sleep <interval>` as the entry-point command,  `Ctrl+C` control signal is not being responded to by the `kubectl`. 

Only way to kill this process seem to be `kill -TERM $(pidof kubectl run)` or `kill -9 $(pidof kubectl run)`.

**What you expected to happen**:
`kubectl run` to honor `Ctrl+C` 

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl run t1 -q --rm -i --tty --image ubuntu:18.04 --image-pull-policy IfNotPresent --restart Never --command -- sleep 120` Run the above command and hit `Ctrl+C`

**Anything else we need to know?**:
```bash
# Test to Check if the normal sleep command is responding properly to the Ctrl+C
❯ sleep 100000
^C

# Run to see if the kubectl run with sleep is responding to the Ctrl+C
❯ kubectl run t1 -q --rm -i --tty --image ubuntu:18.04 --image-pull-policy IfNotPresent --restart Never --command -- sleep 120
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^Z^X^X^X^Z^Z^Z^Z^Z^Z^Z^Z^X^X^C^C^C
```
Tried to validate the same by changing the `intr` binding 
```bash
# Change binding
❯ stty intr ^G

# Test to Check if the normal sleep command is responding properly to the Ctrl+C
❯ sleep 100000
^G

# Test to Check if the normal sleep command is responding properly to the Ctrl+C
❯ kubectl run t1 -q --rm -i --tty --image ubuntu:18.04 --image-pull-policy IfNotPresent --restart Never --command -- sleep 120
^G^G^G^G^G^G^G^V^V^V^C^C^C^C^C^X^X^X^X^Z^Z^Z^Z^Z
```
Some other combinations
```bash
❯ kubectl run t2 -q --rm -i --tty --image ubuntu:18.04 --image-pull-policy IfNotPresent --restart Never --command -- bash -c 'sleep 10000'
^C^C^C^C
```
Above one has the same behavior while the following works fine. 

```bash
 kubectl run t2 -q --rm -i --tty --image ubuntu:18.04 --image-pull-policy IfNotPresent --restart Never --command -- bash -c 'cat > /tmp/test'
^Cpod default/t2 terminated (Error)
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```bash
❯ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-30T06:34:50Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
NA
- OS (e.g: `cat /etc/os-release`):
```bash
❯ uname -a
Darwin TARDIS 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64
````

**Comment by MaGaroo** [comment]
+1

Having the same problem in version 1.23.

`kubectl run test-pod --rm -it --image ubuntu:18.04 -- sleep 10`

**Comment by ardaguclu** [comment]
@harshanarayana @MaGaroo thanks for raising this issue.

@harshanarayana in your case you are passing `--command` flag but you are only setting command `sleep 120` for the container and that's why, in reality `kubectl run` command can not be attached to the container because there is no additional command to be used by attaching. It simply hangs and thus, ctrl+c is not working.
Instead if I pass for example `kubectl run t1 -q --rm -i --tty --image ubuntu:18.04 --image-pull-policy IfNotPresent --restart Never --command -- sleep 120 sleep 120`, I can exit successfully. 

@MaGaroo I tested your command on latest version 1.27 and I can also exit without any problem and I'd suggest updating your kubectl.

But I totally accept that there are a lot of flags in `kubectl run` command which might mislead and hurt user experience.
Since there seems to be no bug just bad user experience stem from kubectl run, I'm closing this issue. If you think, I'm missing something, feel free to re-open it. Thank you.

/close
