### ISSUE TITLE
kubectl watch bails after first event

### ISSUE THREAD

**Issue by nrobert13** [kubernetes/kubectl#1449]
### What happened?

running `kubectl get --watch nodes | awk '{print}'` or `kubectl get --watch nodes > out.txt` bails after the first event. Same happens with `--watch-only`.

### What did you expect to happen?

it continues running just like if the output is a terminal.

### How can we reproduce it (as minimally and precisely as possible)?

`kubectl get --watch nodes | awk '{print}'` or `kubectl get --watch nodes > out.txt`

### Anything else we need to know?

It seems that it bails if the output is not a terminal.

### Kubernetes version

<details>

```console
$ kubectl version
# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-14T09:49:08Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# Darwin ***** 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000 arm64

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ardaguclu** [comment]
I could not reproduce it, after applying the following steps;
```sh
$ kubectl get pods --watch
$ kubectl apply -f test_pod.yaml # different terminal
```
`kubectl get pods --watch` did not exist and continued watching.

Could you please provide the exact steps to reproduce this?. Thanks.

**Comment by nrobert13** [comment]
I thought I did it in my post. I guess you are not following the steps I provided. You have to either pipe or redirect the output of the watch...

**Comment by ardaguclu** [comment]
I also redirected the output of `kubectl get pods --watch` and it worked which proves that this works when watching pods. There might be a problem for nodes when _specific_ type of event occurs but I still can't see this detail in your description.

**Comment by nrobert13** [comment]
I'm wondering what is the point of providing the steps to reproduce, if you don't use them.... would it make sense if you try to reproduce with the steps I provided, instead of complaining about the details provided?

**Comment by brianpursley** [comment]
> I'm wondering what is the point of providing the steps to reproduce, if you don't use them.... would it make sense if you try to reproduce with the steps I provided, instead of complaining about the details provided?

Please try to be patient with contributors who are trying to help you.

As for the issue.  I have some follow-up questions for you:
1. Does this only happen when watching nodes? For example, if you watch pods, do you experience the same problem?
2. When the kubectl command exits, do you get a nonzero exit code?
3. If you run with verbose logging, do you see anything that indicates why it stops? Could you post the output from `kubectl get --watch nodes -v9 > out.txt` when the problem happens?
4. Are you watching nodes because nodes are being added/removed over that period of time?  And if so, then if your control plane becomes unavailable, I could imagine the watch stopping. I'm just trying to think of a reason why this could happen. I'm trying to understand what changes are occurring to your nodes when this problem happens. When I run `kubectl get --watch nodes > out.txt` like you said to do, the problem doesn't happen for me, but then again, no changes are happening to my nodes either. So there must be something more to it.

**Comment by nrobert13** [comment]
hi @brianpursley , thanks for the reply. The `-v9` was very insightful. I was running with `--request-timout 3` and it seems that was the culprit.
```
I0714 17:03:44.178077   33313 streamwatcher.go:114] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout or context cancellation while reading body)
```

**Comment by mpuckett159** [comment]
/close
If this issue was not resolved please feel free to re-open.
