### ISSUE TITLE
Mention namespace in "pods not found" error message

### ISSUE THREAD

**Issue by Expurple** [kubernetes/kubectl#1459]
Hi, I'm a newish user. Recently I had the following situation:

1. I ran `kubectl get pods -n my-namespace` and saw a crashed pod.
2. I copied the name of the pod and ran `kubectl logs my-pod-name`. It returned
    ```
    Error from server (NotFound): pods "my-pod-name" not found
    ```
3. For some time, I really couldn't understand why. Ran `get pods` again. The pod is right there!
4. A colleague pointed out that I needed to run `kubectl logs my-pod-name -n my-namespace`.

I understand the concept of namespaces. I've already encountered and used them before. But still, I made this mistake and couldn't figure it out.

**Please mention the namespace in the error message:**

```
Error from server (NotFound): pods "my-pod-name" not found in namespace "default"
```

This should probably be done for all commands that operate on namespaced entities.

**Comment by mpuckett159** [comment]
It actually looks like we are already trying to do this [here](https://github.com/kubernetes/kubernetes/blob/9ee7185be6d613f2296bc10c6cb83406ee55fcee/staging/src/k8s.io/kubectl/pkg/cmd/get/get.go#L562-L570), but because the error is provided from the server itself (this is controlled by apimachinery I believe) that means we don't get down to this chunk of code. We will either need to update the error provided by apimachinery or check for this specific error and handle that case. Unsure whether to accept or not. I think we can fix this on the kubectl side but it would be best to handle on the apimachinery side I believe.

**Comment by HirazawaUi** [comment]
> It actually looks like we are already trying to do this [here](https://github.com/kubernetes/kubernetes/blob/9ee7185be6d613f2296bc10c6cb83406ee55fcee/staging/src/k8s.io/kubectl/pkg/cmd/get/get.go#L562-L570) 

Doesn't seem relevant here.

We can determine if the call apiserver error is `NotFound`, and append the namespace name to the `NotFound` error.

A simple demo:
```diff
	allErrs := []error{}
	errs := sets.NewString()
	infos, err := r.Infos()
+
+	if apierrors.IsNotFound(err) {
+		err = fmt.Errorf("%w in namespace %s", err, o.Namespace)
+	}
```

But that would require sig cli members to decide if this change is necessary or not.

**Comment by mpuckett159** [comment]
/triage accept
Yes the point of me referring to that is that it was something that we were already trying to accomplish but was not happening due to a bug. Forgot to add the accepted tag.
