### ISSUE TITLE
PAGER and KUBE_PAGER environment variable support

### ISSUE THREAD

**Issue by reegnz** [kubernetes/kubectl#1489]
**What would you like to be added**:
When a user has a `PAGER` or `KUBE_PAGER` environment variable configured, kubectl should pipe it's output through that pager if the stdout is a tty.

**Why is this needed**:
Respecting the user's configured `PAGER` environment variable would allow for better user experience, just like respecting `EDITOR` and `KUBE_EDITOR` does today when running `kubectl edit`.
Scrolling through json or yaml output with the configured pager (eg. `less` or `vimpager`) integrates well into the linux ecosystem of pagers and would align kubectl with other tools that respect the `PAGER` variable.

**Comment by MaGaroo** [comment]
I can work on this issue once it's triaged.

**Comment by MaGaroo** [comment]
Just wondering, what to do if `pager` executable exists in `$PATH` but none of the environment variables (PAGER/KUBE_PAGER) are set? Should kubectl use pager or just print the text to stdout? What do other tools do in similar circumstances?

**Comment by apelisse** [comment]
What is `pager` in your example? Are you referring to an actual binary called `pager`?

**Comment by MaGaroo** [comment]
> What is `pager` in your example? Are you referring to an actual binary called `pager`? I'm not aware of any convention where `pager` means anything.

```bash
$ which pager
/usr/bin/pager
$ ls -l $(which pager)
lrwxrwxrwx 1 root root 23 Feb 20  2022 /usr/bin/pager -> /etc/alternatives/pager
$ ls -l /etc/alternatives/pager
lrwxrwxrwx 1 root root 13 Feb 20  2022 /etc/alternatives/pager -> /usr/bin/less
```

**Comment by reegnz** [comment]
If it's OK to add distro-specific logic into kubectl then go ahead.
But IMHO adding distro-specific behaviour belongs into distro-package patches.

Since /etc/alternatives/pager does not exist in Fedora, various RHEL flavours (Rocky, Alma, AmazonLinux, OracleLinux, etc.) I think it does not make much sense to be preferential about debian-based linux.

**Comment by MaGaroo** [comment]
> If it's OK to add distro-specific logic into kubectl then go ahead. But IMHO adding distro-specific behaviour belongs into distro-package patches.
> 
> The `/etc/alternatives/pager` is definitely not standard, it does not exist in Fedora, or various RHEL flavours (Rocky, Alma, Amazon, Oracle, etc.). I think it does not make much sense to be preferential about debian-based linux.
> 
> I'd say just don't use a pager if the env var is not defined.

Totally agree.

**Comment by MaGaroo** [comment]
Can you please review this PR so I know I am going to the right direction or I'm completely wrong? 👀
kubernetes/kubernetes#120946

**Comment by mpuckett159** [comment]
This should be a shell function or something similar imo, e.g.:
```shell
kubectl () {
        command kubectl "$1" | pager
}
```

Add the function to your RC file or something. Reason for this is that this would be something extra for kubectl to be responsible for that is very distro specific, and it can be solved using shell scripts rather than adding functionality (and more code) to kubectl that will then need to be supported going forward.

**Comment by MaGaroo** [comment]
@mpuckett159 
I agree that keeping it out of kubectl would make the work of kubectl maintainers easier, but I don't agree (yet) that it's really out of scope. I have two reasons:
1. It needs some context that's already known by kubectl, but not by a blind shell function. For example, pager should not be used for some commands like `exec`, or it's behavior might be a little different when `--watch` flag is passed to some commands like `get`. Also, the pager should not be used when stdout is not a tty (e.g. `kubectl get pods | grep pattern`)
2. This one isn't really a logical reason but makes me doubt. I'm just wondering why the developers of `git log` or `man` decided to handle pager themselves instead of forcing the users to define a shell function or something for paging the output.

**Comment by reegnz** [comment]
@mpuckett159
A simple shell script you provided cannot shim the pager functionality. It's at least 100 lines or more, because one would have to partially reimplement the kubernetes command parsing in bash to determine what commands NOT to use a pager for (eg.: edit, port-forward, attach, debug, exec, and I haven't even talked about subcommands). Also having to be mindful of the output being a tty or not (eg. when kubectl output is piped to another command you most definitely don't want a pager gobbling up everything in-between).
Also PAGER is fully distro-agnostic, it's an environment variable.maybe stdin/stdout piping works differently in windows, but definitely works the same across linux and various different BSD flavours. For example I'm on MacOS and I 100% do want PAGER, as it's a distro (and OS) agnostic solution.

**Comment by mpuckett159** [comment]
The example script was not meant to be a functional solution merely an example. You can make the script aware enough to run only on a subset of commands.

You'll have to ask the git and man maintainers why they decided to include native support for this.

Distro support is not the right words, I should say rather support for a very specific tool that is not maintained or controlled by the Kubernetes project or sig-cli. This tool is outside our scope and I think makes this out of scope for the project because it's possible to write your own integration that doesn't require access to the guts of kubectl. There are already issues that I've been added to even this month for external tools kubectl integrates with natively that need extra support, and these tools are fundamental to the commands they support, so I am saying this now with that in mind to reduce the surface area of potential issues arising from adding support for this.

Also it was said the shell script would require "at least 100 lines" to implement because you would have to reimplement kubectl's command parsing. Unfortunately it is not any easier in the internals of kubectl. There will likely need to be many lines over several files added to support this feature. You would still need to implement much of the logic mentioned in kubectl directly.

**Comment by MaGaroo** [comment]
I'm almost convinced. So, I closed the PR.

**Comment by ardaguclu** [comment]
I agree that we shouldn't add any logic in kubectl depending on external binaries. This can be managed via plugin or aliases, etc. rather than an implementation in kubectl. I'm closing this issue, feel free to reopen it if you think I'm missing something. Thanks.

/close

**Comment by reegnz** [comment]
< I agree that we shouldn't add any logic in kubectl depending on external binaries
Just as a closing note, you already do depend on external binary when choosing the user's own EDITOR when doing `kubectl edit`.

**Comment by em-** [comment]
I'd love to be able to see this implemented with a shell function, but I really can't see how it can reliably distinguish `kubectl $A_BUNCH_OF_PARAMS get $OTHER_PARAMS` from `kubectl $A_BUNCH_OF_PARAMS edit $OTHER_PARAMS` to avoid triggering the pager in the latter case.

Arguably, even `kubectl get --watch` should not trigger the pager, so I agree it is likely complex to deal with even from inside the `kubectl` codebase, but it is definitely harder to deal with it from outside.

Another big drawback of the piping approach is that `foo | pager` by default reports the exit status of `pager`, not the `foo` one. It can be worked around, but it is yet another hurdle and there are enough of them that I do not think it is reasonable to implement this as a shell function.

For reference, here are a few Go modules implementing the "use a pager if any of them can be found in the $PATH and stdout is actually a terminal":

* https://pkg.go.dev/go.chromium.org/luci/common/system/pager
* https://pkg.go.dev/github.com/gerow/pager
* https://pkg.go.dev/github.com/jackdoe/go-pager

**Comment by lennartack** [comment]
Kubecolor now has pager support. https://github.com/kubecolor/kubecolor
