### ISSUE TITLE
Concurrent `kubectl apply` for the same resource

### ISSUE THREAD

**Issue by juliev0** [kubernetes/kubectl#1550]
I'm not sure if this is a bug or maybe a design choice. Would like to find out. 

**What happened**:

1. Execute a `kubectl apply -f` on a resource which already exists and put a breakpoint directly prior to the patch being applied [here](https://github.com/kubernetes/kubectl/blob/b73518af09755bb9607e8755e7fc111ee1adceb5/pkg/cmd/apply/patcher.go#L205), 
2. Execute a separate `kubectl apply -f` on the same resource but with a slightly different definition and allow it to go through. This one sets FieldA, which was not set in the Step 1 Resource and was not in the "last-applied-configuration" prior to Step 1.
3. Continue from the breakpoint of the apply from Step 1: this one also succeeds. 
Result is a combination of the two definitions. 

Step 3 Patch does not include anything related to FieldA, and so it is still in the Resource.

**What you expected to happen**:

Theoretically, it seems like the last apply to go through should win. 

**How to reproduce it (as minimally and precisely as possible)**:
See "What happened" section. 

**Anything else we need to know?**:

**Environment**:

- Kubernetes client and server versions (use `kubectl version`):
Run from latest master cloned from github.com/kubernetes/kubernetes
```
% go run ./cmd/kubectl/kubectl.go version                                
Client Version: v0.0.0-master+$Format:%H$
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.4+k3s1
```
- Cloud provider or hardware configuration: M1 Mac
- OS (e.g: `cat /etc/os-release`): Sonoma

**Comment by mpuckett159** [comment]
See the note in the below link for more details. Basically yes this is expected behavior because apply uses the patch method, not a put method, for it's functionality, which is a partial in place modification as opposed to replace which sets the object entirely (that would be an http put method). You can see the line that you linked in the original issue shows that apply is using a patch method to accomplish this task. If you were to edit the same field then the last applied would win, but because you are editing two different fields there is no conflict and so both values are applied in the resource definition.

https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/#declarative-object-configuration

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT

/close

**Comment by juliev0** [comment]
> See the note in the below link for more details. Basically yes this is expected behavior because apply uses the patch method, not a put method, for it's functionality, which is a partial in place modification as opposed to replace which sets the object entirely (that would be an http put method). You can see the line that you linked in the original issue shows that apply is using a patch method to accomplish this task. If you were to edit the same field then the last applied would win, but because you are editing two different fields there is no conflict and so both values are applied in the resource definition.
> 
> https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/#declarative-object-configuration
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT
> 
> /close

Thank you! Just a quick question as to whether Server Side Apply would take care of this problem? I guess it probably doesn't since it also uses PATCH. It does seem that if the ResourceVersion were incorporated into the patch, then maybe it would, but the ResourceVersion is not contained in a user-defined Spec.

**Comment by mpuckett159** [comment]
Yeah even with server side apply, the method used is still a patch method and so the patch strategy will govern how the patching process works. I'm not 100% sure but I believe it is mostly merging therefore if there is no key collision the patch strategy will merge the two objects. If there is key collision the one with the most recent version will win.

**Comment by juliev0** [comment]
Really appreciate the responses. 

> believe it is mostly merging therefore if there is no key collision the patch strategy will merge the two objects.

So, in this case I guess we're basically talking about two goroutines running on the K8S Server (in one or more Pods), each handling a different request. If each one maybe does a `Get` from etcd, and performs a merge with the incoming patch, then perhaps there is in fact a ResourceVersion on that final Object, and then the second request gets rejected? (Not sure if this makes sense, and also since this is related to K8S Server, I can totally take the question there or find the relevant code myself.)

Thank you!

**Comment by mpuckett159** [comment]
Yeah unfortunately I do not know the exact mechanisms of how the apply requests are handled on the API server side of the house, but basically the result of this is that two applies made at the same time will race to be completed. Because applies are done via PATCH they are partial in place updates of resources, and therefore you will not see one apply finish and then the second apply overwrite the first one, you will see a merge of the two apply manifests as the resulting resource. Essentially, there is no bug here as far as we (SIG-CLI) are concerned, apply is a patch, and this is documented in the feature as well as the code. There are other methods to use PUT style methods, but apply does not make use of this.

**Comment by juliev0** [comment]
> Yeah unfortunately I do not know the exact mechanisms of how the apply requests are handled on the API server side of the house, but basically the result of this is that two applies made at the same time will race to be completed. Because applies are done via PATCH they are partial in place updates of resources, and therefore you will not see one apply finish and then the second apply overwrite the first one, you will see a merge of the two apply manifests as the resulting resource. Essentially, there is no bug here as far as we (SIG-CLI) are concerned, apply is a patch, and this is documented in the feature as well as the code. There are other methods to use PUT style methods, but apply does not make use of this.

Okay, thank you!
