### ISSUE TITLE
connection drops with `"timed out waiting for the condition" `

### ISSUE THREAD

**Issue by lcmgh** [kubernetes/kubectl#1556]
**What happened**:

```bash
kubectl --context <alias> \
        run <pod_name> \
        --restart=Never \
        --image=alpine/socat:1.7.4.4 \
        --labels=target_host=<short_db_name>,target_port=<target_port>,deployer=$(whoami) \
        -it \
        --rm \
        --port=<target_port> \
        --command -- \
        timeout 8h \
        socat \
        tcp-listen:<target_port>,fork,reuseaddr \
        tcp-connect:<target_hostname>:<target_port> 
```
After ca. 1min the POD is being dropped and it fails with error `"timed out waiting for the condition" `. The issue does not occur when adding `--pod-running-timeout=8h`.

However `--pod-running-timeout` is unrelated to `kubectl run` and only [documented](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_wait/) for `kubectl wait`.

**What you expected to happen**:
* The connection/pod not being dropped

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Might be related to https://github.com/kubernetes/kubectl/issues/1477 as it looks to me that the wait cmd is utilized internally.

**Environment**:
Client Version: v1.28.3 / MacOS / Windows

**Comment by mpuckett159** [comment]
/close
We have been having issues with our auto-generated documentation (like that found at the site you linked to) and this is a result of that. While we work on fixing this issue with sig-docs, please consider the help text from the command (e.g. here `kubectl run --help`) the source of truth for flags and documentations. I am going to close this issue as the underlying issue is the documentation which has already been triaged and is being worked on.
