### ISSUE TITLE
allow specifing resource uid for kubectl commands

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes/kubectl#1560]
**What would you like to be added**:
kubectl commands reference resources by namespace/names which can cause race conditions when running multiple commands in sequence.
It would be nice if we could specify the uid of a resource being operated on instead of the name or in addition to the name.
For example:

    kubectl delete pod -n $namespace $podname/$uid

Will only execute a delete on a pod with this exact uid and not another pod with the same name which may have been created by a e.g. a statefulset.

**Why is this needed**:
When fetching resources with kubectl and then operating on them there is the chance that the resource has been changed in the meantime.
Typically this would be handled via the resource version which also cannot be set for all operations, but that may also not be suitable for some cases.
For example when waiting for a pod deletion:

    kubectl delete pod --wait=false $pod # or deleted via kubectl drain node
    kubectl wait --for=delete $pod

If the pod has been recreated with the same name (which is common for e.g. statefulsets) the wait will hang on the new pod that was never deleted.

If we could specify the uid this could be avoided.

(For this wait --for=delete usecase a flag to not wait on pods without deletionTimestamp would be sufficient too)

**Comment by ah8ad3** [comment]
I might be wrong but i think we have the mechanism of checking `UID` on wait for delete but i couldn't find the initialization on `UIDMap` if the chair agree on adding a mechanism on receiving an `UID` from command line maybe this can get fixed.
https://github.com/kubernetes/kubernetes/blob/ed84e7f6d327d518e140c5f9c31462075b922c3a/staging/src/k8s.io/kubectl/pkg/cmd/wait/wait.go#L375

**Comment by mpuckett159** [comment]
/close
The reason that the delete without waiting and then waiting on the next line doesn't work is, as stated, the time between issuing the delete and starting the wait could see the pod being deleted, thus the new pod will be waited on forever, but that's the entire reason the `--wait` flag exists in the delete command, because it maintains the proper resource in the code rather than trying to catch it before it is gone with a second round trip to the API server. This test case is effectively circumventing the code that is already in place to mitigate this.

Additionally, using apply is the generally stated recommendation for sig-cli regarding issues with delete and other imperative commands. Using declarative commands (ie. kubectl apply) is better tested for production use cases and takes into account many more potential factors and cases than the imperative commands (create, run, delete, etc) and is overall much better suited for production workloads.
