### ISSUE TITLE
Documentation update. duration flag in kubectl create token

### ISSUE THREAD

**Issue by harryssuperman** [kubernetes/kubectl#1562]
**What would you like to be added**:

I will like to see in the documentation with:

`kubectl create token -h`

not a duration with a value of 0 seconds.

**Why is this needed**:

If we run the command for help it will be shown following text:

```
 --duration=0s:
        Requested lifetime of the issued token. If not set, the lifetime will be determined by the server automatically. The server may return a token with a longer or shorter lifetime.
```

But if i run the command with 0 seconds i will get following error:

`error: --duration must be positive`

**Comment by mpuckett159** [comment]
/triage accepted
To provide more context for this, the reason that the help text shows the default value being 0s is because of how Go handles unset values for certain types. Because the duration flag accepts a time.Duration type, the null value is 0s, and because when the flag is unset it is declared with no value, that means the default value is thus 0s. The problem is that the API server does not accept a 0s value for this because that is not valid. Instead, if it receives a null value for duration it sets the default value, which presently is 1h. So to fix this we are going to remove the completion logic because it is confusing, and just specify that if a user passes 0s for the duration it will be the same as setting the flag to default which will not pass anything to the API server and will instead set a default value. We should not specify what the default value is because that could change in the future and instead link to some sort of API documentation regarding that.
