### ISSUE TITLE
Show overall readiness in `kubectl get pod` output

### ISSUE THREAD

**Issue by raghavan-arvind** [kubernetes/kubectl#1633]
When you run `kubectl get pod`, you get output like: 

```
NAME                                            READY   STATUS    RESTARTS   AGE
mypod1                                         1/1     Running   0          39m
mypod2                                         1/1     Running   0          39m
mypod3                                         1/1     Running   0          83d
```

which implies that a pod is ready if all of the containers are ready. However, this can be misleading in scenarios where other things impact pod readiness. For example, the AWS Load Balancer Controller supports these pod readiness gates: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/pod_readiness_gate/. If these are failing, the kubectl output will show all containers ready but the replicaset/deployment will show the pod not ready. This makes it look like it's kubernetes itself which is not in a consistent state.

If we could instead show:
```
NAME                                            READY   CONTAINERS  STATUS    RESTARTS   AGE
mypod1                                         True        1/1                    Running    0                    39m
mypod2                                         False       1/1                    Running    0                   39m
mypod3                                         True         1/1                    Running   0                   83d
```

Or find another way to concisely convey this information that would help this issue

**Comment by raghavan-arvind** [comment]
I'm happy to work on this but I would need some feedback:

- Is this change safe? `kubectl get pod` isn't exactly made for programmatic consumption but I wouldn't be surprised if many people are writing scripts like `kubectl get pod | grep <pod name> | cut -d' ' -f2`. 
- Do we think this is the right approach?

**Comment by ardaguclu** [comment]
Could you please provide the reproducing steps?. Because I'm not sure `kubectl get pods` prints containers are ready when containers are actually failing.
Furthermore, I don't think we'd want to change this output as it is clearly not backwards compatible.

**Comment by ah8ad3** [comment]
Arda is right, adding another value here is confusing in future, maybe you can ask about why the pod is not ready in your'e scenario and how to make the api to flag it as not running. Which i believe you can do that by adding some kind of probe (if applicable).

**Comment by brianpursley** [comment]
Does the existing `-o wide` output with the `READINESS GATES` column already provide this information as mentioned [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/pod_readiness_gate/#checking-the-pod-condition-status)?

```
kubectl get pod -o wide
```
```
NAME                          READY   STATUS    RESTARTS   AGE   IP         NODE                       READINESS GATES
nginx-test-5744b9ff84-7ftl9   1/1     Running   0          81s   10.1.2.3   ip-10-1-2-3.ec2.internal   0/1
```

**Comment by GeorgeMac** [comment]
I just wanted to chime in here and see if I can breath a bit of life into this closed issue, as I agree with the sentiment shared by @raghavan-arvind. I think the current `kubectl get pods` default output is misleading in conjunction with `readinessGate`. While it states something accurate (N/N individual containers are ready), it sadly lacks the full information that the pod is not wholely ready. I would assume the `READY` column for `kubectl get pods` would tell me about pod readiness, not solely containers readiness within that pod.

The collective interpretation I have observed amoungst colleagues is that `N/N` under ready means pod is reachable over the network. However, that is not the case with a readinessGate, as the pod is rightfully presented as not ready in the endpoints/endpointslice, until the gate condition reports a True status (which is what we want in terms of behaviour).

While the information is available (as shown through `kubectl get pod -o wide`); I think this is a unfortunate extra step, that if you don't know that `readinessGate` exists (I learnt about these recently after years of using k8s), you would be forgiven for assuming a pod must be reachable over the network when seeing `2/2` all is ready from `kubectl get pods`.

As @raghavan-arvind stated, perhaps this output has ossified now and we can't change it because folks could be attempting to parse kubectl output, which would be a shame. 

One alternative suggestion might be to add an additional bracketed ratio to illustrate the status of readiness gates.
This would conditionally be shown when a pod has at-least one readiness gate defined.

For example:
```
NAME                                 READY         STATUS    RESTARTS   AGE
mypod1                               1/1 (0/2)     Running   0          39m
mypod2                               1/1 (1/2)     Running   0          39m
mypod3                               1/1 (2/2)     Running   0          83d
```

The goal here being to give a signal that I will need to dig deeper (inspect or output wide or output full json) to understand the full state of the pods readiness. More crucially to know that k8s doesn't deem the pod is ready to recieve traffic.
