### ISSUE TITLE
Cached discovery issue on windows

### ISSUE THREAD

**Issue by fabianofranz** [kubernetes/kubectl#18]
From the master branch at least (need to check previous versions), `kubectl get` and potentially a number of other commands are failing miserably on Windows:

```
$ kubectl get pod -v 6
REDACTED
I0518 16:51:47.561501    4196 cached_discovery.go:134] failed to write cache to C:\Users\star\.kube\$master_cluster\servergroups.json due to chmod C:\Users\star\.kube\$master_cluster\servergroups.json.689571775: not supported by windows
```

**Comment by LeiYangGH** [comment]
I still get this error:

I0828 10:05:03.921949   11996 cached_discovery.go:87] failed to write cache to C:\Users\YANG.LEI\.kube\cache\discovery\10.33.62.132_8081\apiregistration.k8s.io\v1\serverresources.json due to chmod C:\Users\YANG.LEI\.kube\cache\discovery\10.33.62.132_8081\apiregistration.k8s.io\v1\serverresources.json.244339038: not supported by windows

**$ ./kubectl.exe  version**
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"windows/amd64"}
