### ISSUE TITLE
Kubectl xpra

### ISSUE THREAD

**Issue by bhack** [kubernetes/kubectl#206]
Can `kubectl exec` work with [xpra](https://xpra.org/trac/wiki/Usage)?
Many dev  wants to access to a GUI in the pod  in the development phase (i.e. for visual debug a job before launching at scale).
The standard way was to install sshd in the pod but if will be possible to connect directly with kubectl I think that could be useful to add a section in the documentation (i.e. access to a X session in the pod).
What do you think?

**Comment by bhack** [comment]
P.s. Just to point on the [Docker related docs](https://xpra.org/trac/wiki/Usage/Docker).

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
