### ISSUE TITLE
kubectl --serviceaccount option use 

### ISSUE THREAD

**Issue by ssubramanian123** [kubernetes/kubectl#210]
Hi,

I have 40+ Deployments which we created before RBAC enabled in our cluster. Now we want to enable RBAC and re-deploy these services. For new deployment, through automated process service account get added, but for the existing deployment either we have to use kubectl edit to modify it or modify existing deployment.yaml file. Since we have 40+ services is there any alternate way to directly pass the service account.

For example 

```kubectl deploy -f mydeployment.ymal --serviceaccount=myserviceaccount ```

or any other best way to add the service account to existing deployments.

Thanks,
Sakthi

**Comment by apelisse** [comment]
I strongly believe you should be editing your `deployment.yaml` files on disk (and then commit them) so that you have a documented/reproducible environment (rather than use edit, or an imperative way of changing the serviceaccount).

You can certainly use a script to change the service account in all files? Though 40-ish is not that bad.

**Comment by apelisse** [comment]
Will that work? I'm really not convinced we should address this issue with more code in `kubectl`. I'll close it unless you really want it :-)

**Comment by liggitt** [comment]
you can use `kubectl set serviceaccount` to set service accounts on an existing deployment, or modify your manifests to include service accounts and reapply them (recommended)

/close
