### ISSUE TITLE
As a user, I want to know exactly what kinflate is going to do and how it will change my resources (8).

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubectl#295]
Suggestion: `diff`
As a user I can see how an ApplicationManifest transforms a set of resources.

- Shows each resource kinflate parses
- Shows how patches are applied
- Shows newly created resources
- Shows label and name changes

**Comment by monopole** [comment]
proposed tasking

1) Add a flag --tmpdir to kinflate that changes
   behavior.  Instead of writing yaml stream to stdout,
   this flag causes kinflate to write a file path to
   stdout representing a newly created tmpdir.  In that
   tmp dir, "kinflate inflate" creates a resource tree
   with file names invented from GVKN.

2) Add a flag --noop that suppresses all transformation.

with these two things the user can enter

  diff $(kinflate inflate --tmpdir -f .) \
       $(kinflate inflate --tmpdir --noop -f .)

To get a diff.

Then we can bury all this in one command

  kinflate diff

if so desired.
