### ISSUE TITLE
Kubectl caches partially populated api discovery

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#41]
Kubectl caches the discovery service results which may not be fully populated by the apiserver.  Kubectl should use etags for caching the discovery service results.

**Comment by liggitt** [comment]
Which commands fail with a partial cache? The intent is to rediscover on cache misses.

**Comment by liggitt** [comment]
@deads2k

**Comment by pwittrock** [comment]
This was being used with `kubectl api-versions` specifically.

**Comment by pwittrock** [comment]
FWIW, I haven't dug into the code to verify the details.  This is just the behavior we are seeing.

**Comment by apelisse** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/cached_discovery.go#L112

If `kubectl api-versions` succeeds once, it will not get updated unless you remove `servergroups.json` (for that specific `host:port`).

**Comment by liggitt** [comment]
I see. For that command, I'd expect it to ask the server every time, since the point of the command is to ask the server for its API versions. Opened https://github.com/kubernetes/kubernetes/issues/48016 to fix that.

In places where kubectl actually asks for a specific kind from the discovery client, it checks if the result came from a cache and retries with fresh data on error (for example, https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/discovery/restmapper.go#L197-L200)
