### ISSUE TITLE
Namespace flag causes completion error.

### ISSUE THREAD

**Issue by AXington** [kubernetes/kubectl#42]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
(Output is current, but this is after I upgraded from 1.6.4 where I first saw the problem)
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:15:53Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:17:51Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): VERSION="16.04.2 LTS (Xenial Xerus)"
- **Kernel** (e.g. `uname -a`): 4.8.0-56-generic
- **Install tools**:
- **Others**: using zsh

**What happened**:
typed: ```kubectl --namespace=$NAMESPACE g``` then hit tab
kubectl threw an error ```kubectl --namespace=foo g__handle_flag:25: bad math expression: operand expected at end of string```

**What you expected to happen**:
g would complete to 'get'

**How to reproduce it** (as minimally and precisely as possible):
enter ``` kubectl --namespace=foo g``` and hit tab

**Anything else we need to know**:
Does not happen without the --namespace flag

**Comment by superbrothers** [comment]
This is not an issue specific to --namespace. It can happen with all flags in the format --flag=val in zsh only.
```
$ kubectl --context=minikube __handle_flag:25: bad math expression: operand expected at end of string
```

Then, I found that this issue is caused by the flaghash variable in __start_kubectl() to be not a global variable. The following is the minimum reproduction code.
https://gist.github.com/superbrothers/6427b3a7853aa4043dc436189794245a

The following is the fixed code.
https://gist.github.com/superbrothers/41cdb44d30658c42ab5df8b936a66eb8

This issue is complicated because the code in the flaghash part is generated by cobra, but cobra does not support zsh. It is implemented by kubectl.
https://github.com/spf13/cobra/blob/8c6fa02d2225de0f9bdcb7ca912556f68d172d8c/bash_completions.go#L259

There are two ways to fix this issue.
1. Create a PR that fixes the flaghash variable in cobra/bash_completion.go to be a global variable.
    - https://github.com/superbrothers/cobra/commit/d4ea9c4fcd6fc1d2b1ed5ec9de87a3f1e4a35da8
    - As bash works fine, so is this PR appropriate for cobra?
1. Convert the flaghash variable to be a global variable by __kubectl_convert_bash_zsh().
    - https://github.com/superbrothers/kubernetes/commit/174a1e952c31be5ae95540b5447394d8a76ff12c
    - This way is vulnerable to changes in cobra.

I've tested both changes with both bash and zsh.

**Comment by mengqiy** [comment]
@superbrothers If you think this is a bug for cobra, you can try to fix it upstream.

**Comment by superbrothers** [comment]
@mengqiy I was thinking about this, I found out that this is not a bug for cobra. I will create a PR for kubectl.
