### ISSUE TITLE
kubectl delete returns incorrect exit status

### ISSUE THREAD

**Issue by tnozicka** [kubernetes/kubectl#57]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.2074+858d9d485741f6", GitCommit:"858d9d485741f671f45d39a801c99213f68084ad", GitTreeState:"clean", BuildDate:"2017-08-17T15:47:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0+695f48a16f", GitCommit:"d2e5420", GitTreeState:"clean", BuildDate:"2017-08-29T12:41:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
`kubectl delete` returns bad exit status. It was unable to delete specified resources and exited with code 0.

**What you expected to happen**:
Exit with non zero exit code.

**How to reproduce it** (as minimally and precisely as possible):
```
$ kubectl delete po --ignore-not-found=false -l foo=bar --grace-period 0 && echo $?
No resources found
0
```

**Comment by apelisse** [comment]
That's arguable. That command line `kubectl delete pod --ignore-not-found=false -l foo=bar ...` doesn't have a specific resource to delete, but a label of resources to find and delete.

Finding no resource that match a label is pretty different from failing to find the specific item you wanted to delete. In other words, it didn't fail to delete any of the matching items, it just didn't find any.

On top of that, even if this was indeed a bug, we don't know if people are using it as a "undocumented feature" in existing script, and changing that behavior would be an unexpected change for people of the interface.

WDYT?

**Comment by apelisse** [comment]
Generalizing a little bit more. What about `kubectl get pods`? When the cluster is new and no pods are running, doing `kubectl get pods` returns "No Resource Found" (without errors). I don't think that should be a failure. 

Similarly, if you say `kubectl get pods unknown-pods`,  that should fail if `unknown-pods` doesn't exist. 

And similarly, `kubectl get pods -l some-label=no-exist` returns "No Resource Found" (without errors) if no pods match that label description, because it's just supposed to filter pods that match the label. And if there are none, I really don't think it's a failure.

**Comment by apelisse** [comment]
No updates, closing
