### ISSUE TITLE
Inscrutable error message.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [kubernetes/kubectl#573]
**Kubernetes version** (use `kubectl version`):

> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5", GitCommit:"d776b4deeb3655fa4b8f4e8e7e4651d00c5f4a98", GitTreeState:"clean", BuildDate:"2018-11-08T20:33:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

Linux and Windows.  I tried on both platforms.

**What happened**:
```
rennie@cloudshell:~/csharp-docs-samples/appengine/flexible/SocialAuth (dotnet-docs-samples-tests)$ kubectl apply -f social-auth-deployment.yaml
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
The Deployment "social-auth" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"run":"social-auth", "app":"social-auth"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**What you expected to happen**:

A useful error message.  I got rid of the error message by deleting my existing deployments.  Nothing in the error message indicates that the problem is with an existing deployment.

**Comment by SurferJeffAtGoogle** [comment]
Has the error message improved?

**Comment by SurferJeffAtGoogle** [comment]
I've learned a lot about Kubernetes in the past 8 months, and I still find this error message opaque.

**Comment by soltysh** [comment]
There are 2 problems in here which might be confusing, so lemme shed a bit of light:
```
rennie@cloudshell:~/csharp-docs-samples/appengine/flexible/SocialAuth (dotnet-docs-samples-tests)$ kubectl apply -f social-auth-deployment.yaml
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
```
This warning is indicating you're invoking apply on a resource which was not created with `kubectl apply` command, or appropriate flag passed to `kubectl create`. The reason for that is using either will add an annotation to the object so the next invocation can compare that and pick what has changed and apply correct patch. Since you're initial invocation did not used that, that particular annotation is empty and thus when updating your deployment using `kubectl apply` you're seeing:
```
The Deployment "social-auth" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"run":"social-auth", "app":"social-auth"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
which is an error coming from the server because you're trying to modify Deployment's spec.selector field. Even though you might not be aware of it. This is because after submitting a deployment to the server one of the steps involves defaulting, which amongst all creates a unique selector for your deployment. Since your initial deployment creation was without that annotation the comparison is made against the empty annotation, your new value and what server has. This shows a change in the selector field and a patch is issued removing that server-side added element. 

I don't think we can make the message any more clearer than it is currently. The tl;dr here is use `kubectl apply` consistently when working with your resources and you won't have these problems. Also newer versions of `kubectl apply` are don server-side which should be free from those problems.

/close
