### ISSUE TITLE
Return list of operation ids from 'kubectl apply' and add 'kubectl await' to wait for their results

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubectl#59]
**FEATURE REQUEST**

I use `kubectl apply` to perform rolling updates for _Deployments_, rolling updates for _StatefulSets_, updates for _Deamonsets_, etc. Usually with multiple manifests in one file (namespace, secret, service, deployment).

To verify whether those updates finish successfully I currently need to figure out which one - or combination - of the above actions I just applied. Nicer would be if `kubectl apply` returns a list of operation IDs for every manifest in the applied file, whether it's a namespace, a service account, a secret, a deployment or any other type of object in Kubernetes.

Armed with this list of operation IDs another kubectl function could either monitor them individually or all at once to see progress.

For this a new command like `kubectl await` - or another possibly better command name - could monitor the operations until they either succeed or fail. It could be an alias for commands like `kubectl rollout status deploy/nginx-deployment` that blocks until it's either completed successfully or failed and returns an exit code of 0 or 1 depending on this success. The `kubectl await` would work for any type of object creation, update, etc action that's the result of `kubectl apply`. And multiple of those actions running at the same time.

In pseudo code

**apply the manifest**
```
operationIDs []int := kubectl apply -f <filename>
```

**await the operations to finish**
```
kubectl await <operationIDs>
```

I'm not sure if every operation in Kubernetes already gets and ID and if there are any functions available that could already help with the above. Looking forward to hear more about it.

**Comment by apelisse** [comment]
I think I agree with all of that, but the choice of `await` as a keyword kind of confused me.

Would you mind updating the description of the issue to include an expected output for `kubectl await ...` ?

**Comment by JorritSalverda** [comment]
I've added a description on what `kubectl await` - or whatever name covers its meaning :) - is expected to do.

**Comment by paulgmiller** [comment]
#54932 might be related

**Comment by ashi009** [comment]
How come a feature like this is ignored for all these years.  For a managed rollout, the result of the `kubectl apply` should provide enough information for the automation system to make the verdict, instead of guessing the status of the rollout. 

OTOH, two separate calls made with `kubectl` are not naturally bound. I think it would be more preferable to let `kubectl apply` to watch the rollout directly.

**Comment by MPJHorner** [comment]
Did you come up with a solution for this or is their an alternative way to do the rolling update and check the outcome?

**Comment by paulgmiller** [comment]
Nothing new from me

On Jul 20, 2018 9:44 AM, "Matt Horner" <notifications@github.com> wrote:

Did you come up with a solution for this or is their an alternative way to
do the rolling update and check the outcome?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubectl/issues/59#issuecomment-406658035>,
or mute the thread

**Comment by seans3** [comment]
This functionality is not on the kubectl roadmap. Please reference "kubectl rollout status ..." or "kubectl get --watch ..."

Closing this.

**Comment by apelisse** [comment]
Not completely true, that sounds very similar to what @monopole is doing.
