### ISSUE TITLE
Deprecate "Discovery" and replace with openapi

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubectl#66]
This is a feature request, or an invitation to discuss the above idea.

The cache mechanism for discovery is far from perfect, and there is quite some code that we could remove from kubectl by using openapi rather than the current discovery mechanisms.

I'll try to investigate what this would mean, but I think that no so many things would be impacted.

cc @pwittrock @mbohlool 

*Please cc whoever might find this relevant.*

**Kubernetes version** (use `kubectl version`): kubectl 1.8

**Comment by apelisse** [comment]
FYI @smarterclayton @liggitt

**Comment by liggitt** [comment]
openapi for schema seems reasonable, but I would not expect to stop using the group/version/kind discovery docs which convey structure and precedence information not present in the openapi docs

**Comment by apelisse** [comment]
Can't we get this information from the "paths" section of the openapi?

**Comment by liggitt** [comment]
no. those don't contain the same information as the discovery docs (resource name, shortnames, categories, precedence order). additionally, forcing fetching a single monolithic swagger doc is not scalable as the number of API groups and resource increases (with aggregated APIs). Even creating that aggregated doc has repeatedly proven problematic.

**Comment by mbohlool** [comment]
@liggitt I think:
- we should any missing discovery information to OpenAPI spec as extensions. 
- kubectl is fetching OpenAPI spec anyway. It and make more sense for it to use OpenAPI spec instead of hitting discovery endpoint every time. 
- With aggregated API server, we only have one shortcoming to make this work (adding default spec for endpoints with no OpenAPI spec to add discovery information only). 
- Kubectl or any other client can update their cache of OpenAPI spec efficiently using e-tags.

**Comment by mbohlool** [comment]
related: https://github.com/kubernetes/kubernetes/issues/44589

**Comment by liggitt** [comment]
> related: kubernetes/kubernetes#44589

I am in favor of removing swagger in favor of openapi (no need for two schema descriptors)

> kubectl is fetching OpenAPI spec anyway. It make more sense for it to use OpenAPI spec instead of hitting discovery endpoint every time if possible.

only in the case of client side validation, which we want to remove

> Regarding aggregated API server, we only have one shortcoming to make this work (adding default spec for endpoints with no OpenAPI spec to add discovery information only).

invalidating a multi-megabyte discovery document every time any aggregated API changes any detail doesn't seem like a good idea.

**Comment by mbohlool** [comment]
> invalidating a multi-megabyte discovery document every time any aggregated API changes any detail doesn't seem like a good idea.

Can you elaborate in cases that we change something in the discovery and current OpenAPI spec is not invalidated?

Adding another data point:
- discovery information is cached for 10 minutes in kubectl. So changes in discovery will not be seen by kubectl for a while. But if they are in OpenAPI spec they will be seen instantly (in practice).

**Comment by liggitt** [comment]
The vast majority of the places kubectl uses discovery data, it doesn't need the schema information, it just needs enumerated resources, version precedence, and kind/resource mapping.

Making it fetch a cache-invalidated monolithic discovery doc just for that information isn't desirable.

We'll maintain the existing discovery APIs indefinitely for clients that do not need schema information, and just need the restmapping information (garbage collection, namespace lifecycle controller, etc)

**Comment by apelisse** [comment]
> invalidating a multi-megabyte discovery document every time any aggregated API changes any detail doesn't seem like a good idea.

I'm not disagreeing with that point, but just for the sake of precision, it's actually ~100kb gzipped.

**Comment by apelisse** [comment]
I think my goal was to improve the caching mechanism of discovery, and since we already have a "better" cache for openapi, I thought it'd be nice to just re-use it. But I have to agree with @liggitt on his points.

So the questions is (for another issue probably): can we improve the caching for discovery paths?

**Comment by mbohlool** [comment]
@apelisse @liggitt I think the question here is are we OK with having 10 minutes cache for discovery or not. If we are not, then we can work on another/better cache for discovery or we can rely on already existing OpenAPI cached version. The thing is our performance tests shows that reading <100kb OpenAPI spec on cache invalidation is very fast (especially because it is in proto format) and won't have much toll on the client. 

**Also** I am still waiting for example of cases that invalidate OpenAPI spec (from @liggitt). I don't think they are happening regularly at all, and in most cases, we will hit server to get the same e-tag and not updating any local spec. That would be faster than getting discovery information and also won't have 10 minutes caching problem.

**Comment by apelisse** [comment]
> Also I am still waiting for example of cases that invalidate OpenAPI spec (from @liggitt)
>>every time any aggregated API changes any detail

**Comment by mbohlool** [comment]
@apelisse yes, I am asking for more detail on that. Like an actual example and the frequency of it happening.

**Comment by apelisse** [comment]
OK, closing this now. I think we agree that it's a bad idea. Please re-open if you want this revisited.
