### ISSUE TITLE
Kubectl silently remove all annotation if any of them is set to the string true without quotes

### ISSUE THREAD

**Issue by primeroz** [kubernetes/kubectl#660]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
Tested on 1.12 , 1.13 and 1.14 

**Environment**:
- **Cloud provider or hardware configuration**: GKE and local Kind Cluster

**What happened**:
When applying a manifest for which one of the annotations has the value _true_ unquoted then all annotations are removed when the resource is created on the cluster.

Please see https://github.com/weaveworks/flux/issues/2091 as the original issue that brought me to this conclusion.

From that case you can also see a way to reproduce the issue using KIND and this test repo [here](https://github.com/primeroz/flux-bug-test-repo/)

**What you expected to happen**:
The resource to be created with all the annotations attached and an annotation with the string _true_ 

I would expect an error at least 

**How to reproduce it** (as minimally and precisely as possible):
Follow the example in [this repo](https://github.com/primeroz/flux-bug-test-repo/) using flux or just `kubectl create namespace vault && kubectl apply -f https://github.com/primeroz/flux-bug-test-repo/blob/master/test-cm-no-checksum/ConfigMap-vault-vault-auth-jwt.yaml`

**Anything else we need to know**:

I am not 100% sure this is a kubectl or apiserver validation issue but i felt that if it was the apiserver i would get an error back rather than a silent drop , reason why i am creating this one here

**Comment by pswica** [comment]
If you try to make something with a boolean true with `kubectl create -f` you will get an error as the .json parser converts boolean `true` into an empty string `""` when unmarshalling it into a type `string`. I think there's a bug, but it's from the fact that `kubectl apply -f` let's you create this while ignoring the subsequent annotations, instead of just failing out like `kubectl create` does. I'm still investigating this, though (it's an interesting bug to look into).

**Comment by jlegrone** [comment]
I believe this may be a duplicate of https://github.com/kubernetes/kubernetes/issues/59113

**Comment by primeroz** [comment]
It is a duplicate indeed. closing this one to remove noise
