### ISSUE TITLE
kubectl parameter `--show-kind` combinded with `-o` sometimes is ignored

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/kubectl#669]
`--show-kind=false` does not work when combined with `-o name` 

```
root@master.k1.cluster.local:~# kubectl -n tick-websites get pod
NAME           READY   STATUS    RESTARTS   AGE
chronograf-0   1/1     Running   0          17h
influxdb-0     1/1     Running   0          17h
kapacitor-0    1/1     Running   1          17h

```

```
root@master.k1.cluster.local:~# kubectl -n tick-websites get pod -o wide
NAME           READY   STATUS    RESTARTS   AGE   IP             NODE   NOMINATED NODE   READINESS GATES
chronograf-0   1/1     Running   0          17h   10.244.2.180   zwei   <none>           <none>
influxdb-0     1/1     Running   0          17h   10.244.3.178   drei   <none>           <none>
kapacitor-0    1/1     Running   1          17h   10.244.2.171   zwei   <none>           <none>
```

```
root@master.k1.cluster.local:~# kubectl -n tick-websites get pod -o wide --show-kind=true
NAME               READY   STATUS    RESTARTS   AGE   IP             NODE   NOMINATED NODE   READINESS GATES
pod/chronograf-0   1/1     Running   0          17h   10.244.2.180   zwei   <none>           <none>
pod/influxdb-0     1/1     Running   0          17h   10.244.3.178   drei   <none>           <none>
pod/kapacitor-0    1/1     Running   1          17h   10.244.2.171   zwei   <none>           <none>
```

but

```
root@master.k1.cluster.local:~# kubectl -n tick-websites get pod -o name --show-kind=false
pod/chronograf-0
pod/influxdb-0
pod/kapacitor-0
```

expected:

```
root@master.k1.cluster.local:~# kubectl -n tick-websites get pod -o name --show-kind=false
chronograf-0
influxdb-0
kapacitor-0
```

-------------------

For now I just use formatting with `-o custom-columns=NAME:.metadata.name`, where the kind always is not displayed.

```
root@master.k1.cluster.local:~# kubectl -n tick-websites get po -o custom-columns=NAME:.metadata.name --no-headers=true
chronograf-0
influxdb-0
kapacitor-0
```

and also

```
root@master.k1.cluster.local:~# kubectl -n tick-websites get po -o custom-columns=NAME:.metadata.name --no-headers=true --show-kind=true
chronograf-0
influxdb-0
kapacitor-0
```

**Comment by pswica** [comment]
I have tested this and get the same thing.

**Comment by pswica** [comment]
I tried to fix this in the above PR: https://github.com/kubernetes/kubernetes/pull/79393

**Comment by rdxmb** [comment]
can somebody check the PR, please?

**Comment by soltysh** [comment]
There are two issues here:
1. Unnecessary kind when `--show-kind=false`
2. Printing using `--custom-columns` and `--show-kind`. 

The first case is a bug and should be fixed, there's a `NamePrinter` here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/printers/name.go which most likely is missing wiring the show-kind flag properly.

The latter is not a bug per se, it's impossible to combine the `--show-kind` with `--custom-column` and I'd prefer seeing a PR improving the validation such that these 2 flags can't be specified together.

**Comment by dty1er** [comment]
I made a PR for this issue referring to @rdxmb 's PR  (thank you for your great work).
https://github.com/kubernetes/kubernetes/pull/98904

It seems like the original PR needed some additional changes, so I applied them.
My PR looks containing a lot of file changes, but the reason is written in `Special notes for your reviewer:` part in the PR description. 
I want you guys to help review 🙏

**Comment by brianpursley** [comment]
The problem is that some flags only apply to certain printers. `--show-kind` is only defined by `HumanPrintFlags`:
https://github.com/kubernetes/kubernetes/blob/2a3f28863baa804a05d35c3958a107f9210b4c9e/staging/src/k8s.io/kubectl/pkg/cmd/get/humanreadable_flags.go#L105-L118

`--show-kind` could (should?) probably be elevated to `PrintFlags` like [`NoHeaders`](https://github.com/kubernetes/kubernetes/blob/0486f1a728c964f643c70d1f3aea59243a4fedf8/staging/src/k8s.io/kubectl/pkg/cmd/get/get_flags.go#L41) is, but this reveals another problem in that the default for `--show-kind` is false and the current behavior for `-o name` is to show the kind, so it would be a breaking change for `-o name`.

I'm not saying it can't be done, but just wanted to capture in this comment the challenges associated with making this change.

---

One possible improvement (albeit not a solution) would be to output a warning message if flags are specified which are not used by the chosen output type. so if you tried something like:

```
kubectl get pod -o name --show-kind=false
```

You would get a message something like this:
```
WARNING: the --show-kind flag has no effect when name output is used
```

**Comment by chinglinwen** [comment]
I also found show-kind have no effect when get multiple kind resource.
show-kind flag is override by function `multipleGVKsRequested`.

so that whether to print kind should have a way determined by the user?
