### ISSUE TITLE
Should kubectl describe command display port names?

### ISSUE THREAD

**Issue by Aracki** [kubernetes/kubectl#681]
I can see the port names only by:
`kubectl get pod <pod_name> -o yaml`

...but not with `kubectl describe`. Does the command intentionally miss the names or we can add that? 

I was thinking about making a PR, but not sure if I am missing something important. 👀

Kubernetes version: 1.13.

**Comment by zhouya0** [comment]
I don't think the port's name matters since port can be created without a name. :)

**Comment by eamonryan** [comment]
@zhouya0 I just had this crop up where it turned out something would only take action if a pod's container port had a certain naming convention and I was lost for some time because comparing a working and non-working pod, neither appeared to have any port names at all from the perspective of `kubectl describe`. Only when I used `kubectl get pod <name> -o yaml` on both did I realise there was a different in port names.

Do you think this is worth reconsidering?
