### ISSUE TITLE
error when applying patch is some edge case

### ISSUE THREAD

**Issue by stang** [kubernetes/kubectl#684]
# Issue
We randomly discovered an edge case where the following sequence trigger an error:
```
$ kubectl apply -f manifest-v1.txt 
cronjob.batch/test-cron created

$ kubectl apply -f manifest-v2.txt 
cronjob.batch/test-cron configured

$ kubectl apply -f manifest-v1.txt 
warning: error calculating patch from openapi spec: The order in patch list:
[map[name:b] map[name:b] map[name:c]]
 doesn't match $setElementOrder list:
[map[name:b] map[name:c] map[name:b]]
...
```

Note: `manifest-v1.txt` and `manifest-v2.txt` are both _legal_ objects. In `manifest-v1.txt`, the `.spec.jobTemplate.spec.template.spec.imagePullSecrets` contains dupes but this is considered as valid by kubernetes.

# Environment
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T16:08:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
> Update: this is still the case with kubectl `v1.13.x` and `v1.15.0`

# How to reproduce
```
kubectl apply -f manifest-v1.txt
kubectl apply -f manifest-v2.txt
kubectl apply -f manifest-v1.txt
```
[manifest-v1.txt](https://github.com/kubernetes/kubectl/files/3398908/manifest-v1.txt)
[manifest-v2.txt](https://github.com/kubernetes/kubectl/files/3398909/manifest-v2.txt)

**Comment by seans3** [comment]
/sig cli
/area kubectl
/kind bug
/priority P2

Please note that the version support window is violated in this example (client version 1.15 -> server 1.12), but we'll mark this as a bug anyways. Kubernetes guarantees a +/- 1 version skew. So with the 1.12 server, only kubectl versions 1.11, 1.12, and 1.13 are guaranteed to work. Please reproduce this problem with a supported kubectl version.

**Comment by stang** [comment]
Thanks @seans3! We initially discover the issue using `v1.12` but opened the issue with `v1.15` as I tested it afterward.

I've updated the issue report.

**Comment by richardmarshall** [comment]
This is happening because the strategicpatch code used by client side apply can't correctly create a patch containing a slice of maps with duplicate merge key values.

The error messaging could be improved though to make this less confusing. However with the push to move apply to the server I'm uncertain of how receptive sig-apimachinery would be to changes to strategicpatch which are intended to support improvement to client side apply in kubectl.

@seans thoughts?

>  contains dupes but this is considered as valid by kubernetes.

I would say is a validation bug and duplicate imagePullSecrets should not be permitted. That said this is a core/v1 type we're talking about so fixing that would probably not be worth the level of effort. 😄

**Comment by seans3** [comment]
/cc @apelisse 
/cc @jennybuckley 

Who have context on apply/openapi, and who are working on server-side apply
