### ISSUE TITLE
Unexpected behavior with kubectl run and --env

### ISSUE THREAD

**Issue by kkolk** [kubernetes/kubectl#691]
So, I'm not sure this is the intended behavior or not.  If you execute a pod with kubectl run and the values passed with --env are not always available when the command that was passed is ran.

This set of commands replicates the issue:

`kubectl run busybox --rm -i --tty --generator=run-pod/v1 --image busybox --env MYVAR=sample sh`

Running 'echo "This is my $MYVAR' outputs "This is my sample" as expected.   Now try this instead:

`kubectl run busybox --generator=run-pod/v1 --image busybox --env MYVAR=sample echo "This is my $MYVAR"`

This outputs "This is my " into the logs because $MYVAR isn't set (yet?).

To make this even more confusing:

`kubectl run busybox --generator=run-pod/v1 --image busybox --env MYVAR=sample printenv`

Shows MYVAR correctly set in the output:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=busybox
MYVAR=sample
```

To me this behavior seems really inconsistent.

**Comment by the-gigi** [comment]
It seems that $MYVAR is expanded by the shell BEFORE it is sent to the container. Since, it is not defined in the shell the expanded command that is sent to the container is `echo "This is my "`, which produces the correct output you see.

To verify this is the case try this command:
`MYVAR=4 && kubectl run busybox --generator=run-pod/v1 --image busybox --env MYVAR=sample echo "This is my $MYVAR"`

You should see in the logs `This my 4`

**Comment by kkolk** [comment]
Ah, that explains it.  I can work with that for what I need.  If this is the expected/accepted behavior then feel free to close this issue.

**Comment by enzoTrevisan** [comment]
If you use kubectl to create your pod, then scape $MYVAR  with \  like this
\$MYVAR   
 check your pod with 
kubectl get xxxx -oyaml and you'll see why.
