### ISSUE TITLE
kubectl diff exit code 1 for both errors _and_ diffs

### ISSUE THREAD

**Issue by tomwilkie** [kubernetes/kubectl#707]
It seems `kubectl diff` exits with 1 on both errors (eg for RBAC) or the presence of a diff.  

Would be useful if we could have two different codes here.

**Comment by richardmarshall** [comment]
This makes a lot of sense to me and the actual code implementation would be trivial. The challenge I suppose is what to select as a sentinel error code to indicate an error interacting with the API vs an error with the diff since the diff status code is propagated from an external binary.

The most common case would be GNU diff which will return 0, 1, or 2 giving us a pretty wide window of codes to use. However since users could have anything in their `PATH` for "diff" or override the default diff tool via the `KUBECTL_EXTERNAL_DIFF` env var there is an unknown range of possible exit codes that could be returned by an arbitrary diff tool.

I think it would be reasonable to select a value, I propose 255, and document this in the `kubectl diff` help message. I'll submit a PR implementing this for discussion.

/kind feature
/area kubectl
/sig cli
/assign

**Comment by praseodym** [comment]
It could also make sense to add an option to make the non-zero exit code for the non-error “diff present” optional. One use case is CI for GitOps workflows, I’ve noticed that `kubectl diff` catches mistakes that `kubectl apply --dry-run` does not.

**Comment by sh0rez** [comment]
An alternative to settling on a sentinel error code would be to add an `--exit-status=123` flag that allows users to specify what fits best, but set this to the proposed `255` by default

**Comment by apelisse** [comment]
> One use case is CI for GitOps workflows, I’ve noticed that kubectl diff catches mistakes that kubectl apply --dry-run does not.

`kubectl apply --server-dry-run` would catch these errors and is the recommended way to go. We're promoting server-dry-run and diff to GA this cycle, so we're trying to improve a few things.

**Comment by sanusatyadarshi** [comment]
What is the fix here folks?

I am still seeing the error code as 1.

EKS 1.21( Both client and server on 1.21 including kubectl)

--server-dry-run is unrecognised

**Comment by apelisse** [comment]
Option has become `--dry-run=server`. 

What's the error? Can you show the output?
