### ISSUE TITLE
Write valid JSON from kubectl cluster-info dump

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubectl#816]
**What would you like to be added**:
`kubectl cluster-info dump` writes out cluster info in JSON format, followed by one line:
```
Cluster info dumped to standard output
```
I would like that last line written to standard error

**Why is this needed**:
If the diagnostic is written to standard error, the output becomes valid JSON.

/sig cli

**Comment by sftim** [comment]
The relevant code is https://github.com/kubernetes/kubectl/blob/0555a86aaff9f0ba20dbc066dfaa1891222def87/pkg/cmd/clusterinfo/clusterinfo_dump.go#L292-L294

**Comment by d2iq-shadowbq** [comment]
Precedence for using STDERR for verbosity

https://github.com/kubernetes/kubectl/blob/08c1f25495df730ea63fa7bb6b282e08ac4cd74e/pkg/cmd/plugin/plugin.go#L136

**Comment by brianpursley** [comment]
If dest is stdout, can we just suppress this message entirely?

Regarding the precedent for using stderr for verbosity, I actually just “fixed” that to use stdout 😆 in a recent PR, because I thought it was a mistake.

Kubectl does have a verbose flag that could be used for extra verbosity, and some commands make better use of that than others.

**Comment by sftim** [comment]
> If dest is stdout, can we just suppress this message entirely?

Fine by me!
