### ISSUE TITLE
Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by mshahat** [kubernetes/kubectl#823]
Hi, 
trying to find an explanation to this. 
i am running kubectl on macOS `10.15.3 (19D76)`
```shell
~ ❯❯❯ kubectl version --certificate-authority haproxy-cert/config-dir/live/pks.uat.lnd.xxx.com/cert.pem
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
i have an haproxy setup fronting my kuberentes master api-server, configured to offload TLS them establish another https connection to the backend

```
 frontend fe-https-all-pks-uat-lnd-xxx-com
        bind 172.16.5.100:8443 ssl crt /etc/ssl/certs/pks.uat.lnd.xxx.com.pem
        bind 172.16.5.100:9021 ssl crt /etc/ssl/certs/pks.uat.lnd.xxx.com.pem

        # Cluster 1 Kubernetes Master node
        acl is-cluster-1-master hdr_dom(host) -i cluster-1.pks.uat.lnd.xxx.com
        use_backend be-cluster-1-pks-uat-lnd-xxx-com if is-cluster-1-master

backend be-cluster-1-pks-uat-lnd-xxx-com
        mode http
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request add-header X-Forwarded-Proto https if { ssl_fc }
        server server2 x.x.x.x:8443 ssl verify none
```
I'm using a wildcard `*.pks.uat.lnd.xxx.com` certificate generated from let's encrypt, the root CA for that is `Digital Signature Trust Co. - DST Root CA X3` which i can see found in Keychain Access on my macOS machine, i also marked it as "Always Trust" 

if i use `curl` or `chrome`, the handshake seems to go ok with any issues. if I use kubectl !!!

`kubectl` was not the only client with this problem, i have another cli which has a similar problem. again `curl` and `chrome` had no problem with the communication. 

as part of my investigation, i ran `"$(go env GOPATH)/bin/macos-roots-test"` from https://github.com/golang/go/issues/24652#issuecomment-411069915 , as I had a doubt that it could be a golang issue, at this moment I'm not certain whether it is or not. 
my observation was the following, even though I have it trusted under Keychain Access
```
.
.
crypto/x509: DST Root CA X3 returned 1
crypto/x509: Let's Encrypt Authority X3 returned 2
.
.
crypto/x509: verify-cert rejected CN=DST Root CA X3,O=Digital Signature Trust Co.: "Cert Verify Result: CSSMERR_TP_CERT_SUSPENDED"
crypto/x509: verify-cert approved CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
crypto/x509: ran security verify-cert 26 times
    cgo sys roots: 177.446013ms
non-cgo sys roots: 394.296229ms
The test passed, no need to report the output. Thank you.
```

I also had this thread on letsencrypt with no conclusion! 
https://community.letsencrypt.org/t/macos-catalina-10-15-cn-dst-root-ca-x3/113308

i can have kubectl working if `kubectl cluster-info --insecure-skip-tls-verify `
also if any of the following !!!
```
~ ❯❯❯ kubectl cluster-info --certificate-authority haproxy-cert/config-dir/live/pks.uat.lnd.xxx.com/cert.pem                                                                                                                                          

~ ❯❯❯ kubectl cluster-info --certificate-authority haproxy-cert/config-dir/live/pks.uat.lnd.xxx.com/chain.pem

~ ❯❯❯ kubectl cluster-info --certificate-authority haproxy-cert/config-dir/live/pks.uat.lnd.xxx.com/fullchain.pem
```

also if `kubectl cluster-info --insecure-skip-tls-verif`
Thanks to any points 🙏

**Comment by onesolpark** [comment]
you have to change the `certificate-authority-data` in kube config with your proxy cert
(typically located in `~/.kube/config`)

Example)
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ** changethispart with base64 decoded cert
    server: https://172.28.128.11:6443
  name: kubernetes
```

**Comment by mshahat** [comment]
thanks a million, @onesolpark ... your suggestion is correct, I figured this out a couple of weeks ago and it helped me solve my problem. in my case, i was using a let's encrypt cert, as I commented away the `certificate-authority-data` in `~/.kube/config` , all worked as desired.  

thanks,

**Comment by chiducaf** [comment]
@mshahat  how did you change authority-data in ~/.kube/config

**Comment by suryapandian** [comment]
@onesolpark `certificate-authority-data: ** changethispart with base64 decoded cert`

The decoded certificate looks very bizzare.
To decode a certificate I used `openssl x509 -in ca.cert.pem -text`

I could see multiple headings, like: ` Signature Algorithm`, `Data`, `Version` , `Validity`, `Modulus`, `X509v3 Subject Key Identifie`, `X509v3 Authority Key Identifier` which among these should be used?

When I tried to paste the entire decoded text I get error.

Please suggest.

Thanks

**Comment by cr-noamguy** [comment]
> thanks a million, @onesolpark ... your suggestion is correct, I figured this out a couple of weeks ago and it helped me solve my problem. in my case, i was using a let's encrypt cert, as I commented away the `certificate-authority-data` in `~/.kube/config` , all worked as desired.
> 
> thanks,

Comment it worked!

**Comment by jakubpartyka** [comment]
I'll share my case here since error was the same but cause was different.
For those running kubectl via gcloud utility: you may get this error if something on the cluster changed. Simply re-generate the credentials with
`gcloud container clusters get-credentials --region=<your_region> <your_cluster_name>`
run
`gcloud container clusters list`
to find out name of the cluster

**Comment by FilipposKaragiannis** [comment]
Was getting this error using the gcloud cli and @jakubpartyka suggestion solved the issue. Thanks a lot!!

**Comment by ansh-lehri** [comment]
Hi, 
I am having a OIDC setup similar to @mshahat with few differences. I have instead of haproxy, kube-oidc-proxy in front of my GKE cluster, which I use as reverse proxy to have group based authentication. 
For OIDC provider, I am using dex with GOOGLE as IDP and dex-authenticator (inplace of gangway.)
I'm using a wildcard certificate issued for **"*.xyz.in"**. using this wildcard, I have created a DNS record named **dex.xyz.in** for https request.

Everything works fine initially. i am able to access dex service (dex.xyz.in) using dex-authenticator, it generates suitable kubeconfig file with server flag pointing to kube-oidc-proxy service of LB type, in certificate-authority-data, I use ca.crt value of *.xyz.in as i will be using this same TLS everywhere. i have used this TLS in dex configmap as well and have applied trusted_ca_root config in dex-authenticator with value same as that in kubeconfig.

When i run kubectl commands untill id-token gets expiry, everything works fine. But as soon as id-token get expired, kubect get pods (one example) gives:
 **Unable to connect to the server: Get "https://dex.xyz.in:32000/.well-known/openid-configuration": x509: certificate signed by unknown authority**

This is happening only when refresh-token must be used to get new id-token. Not able to understand why this is happening as i am able to access this URL over chrome and also curl request
`curl --request POST --data ‘client_id=dex-auth&client_secret=<abc>&refresh_token=<pqr>&grant_type=refresh_token’ https://dex.xyz.in:32000/token` works propely and returns appropriate results but kubectl is not able to work with this.

I encountered similar error with dex-authenticator when I was not giving trusted_root_ca field in its configurations. But once I entered that filed, dex-authenticator worked fine.


My kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.2000", GitCommit:"0823380786b063c3f71d5e7c76826a972e30550d", GitTreeState:"clean", BuildDate:"2022-03-17T09:22:22Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by matteosdocsity** [comment]
> Was getting this error using the gcloud cli and @jakubpartyka suggestion solved the issue. Thanks a lot!!

which was the solution? I cannot find it

**Comment by obyerere** [comment]
Hello, I am getting this same error on a freshly Docker desktop environment afte enabling kubernetes i tried the command to see if installed but got error

**Comment by obyerere** [comment]
> Hello, I am getting this same error on a freshly Docker desktop environment afte enabling kubernetes i tried the command to see if installed but got error

I found the answer to this on stack overflow https://stackoverflow.com/questions/71376833/kubectl-giving-error-unable-to-connect-to-the-server-x509-certificate-signed

If you are using Mac OS and newly installed Dicker Desktop the .Kube directory will have to be deleted especially if you already used rancher on the Same Mac OS. so delete .Kube directory then reinit the Kubernetes on Docker Desktop. I added the link where I found answers

**Comment by prudhvi939** [comment]
> you have to change the `certificate-authority-data` in kube config with your proxy cert (typically located in `~/.kube/config`)
> 
> Example)
> 
> ```
> apiVersion: v1
> clusters:
> - cluster:
>     certificate-authority-data: ** changethispart with base64 decoded cert
>     server: https://172.28.128.11:6443
>   name: kubernetes
> ```

@onesolpark. thank for  you suggestion. it worked
