### ISSUE TITLE
How can I use a patches file in the parents' directory?

### ISSUE THREAD

**Issue by hanyouqing** [kubernetes/kubectl#861]
I'm trying to use a common patch file like this:

```
patches:
- ../base/patches/common.yaml
```

then got the error blow:

```
rror: SliceFromPatches: security; file ' ../base/patches/common.yaml' is not in or below '/User/youqing/work/kustomization/apps/development/base'
```

Will it be supported in the coming release? or any suggestion?

**Comment by brianpursley** [comment]
@hanyouqing I don't know for sure, but this seems like an intentional security thing.

One alternative might be to symlink common.yaml into your directory, something like this:
```
ln -s ../common.yaml
```

**Comment by hanyouqing** [comment]
@brianpursley Thanks for your comments, It doesn't work either. actually I've tried that and got the same error.

**Comment by brianpursley** [comment]
@hanyouqing This issue is probably better suited for the https://github.com/kubernetes-sigs/kustomize repository

But I did find this [seemingly related issue](https://github.com/kubernetes-sigs/kustomize/issues/2078) which links to this [FAQ](https://github.com/kubernetes-sigs/kustomize/blob/5d4e45c24dbe5c5aee5c5767a33ee76de2f90f74/docs/FAQ.md#security-file-foo-is-not-in-or-below-bar) which says you can use the `--load_restrictor` flag to disable this security check. But it looks like you will need kustomize v3 for that... so I *think* this means you would need to download and run the kustomize executable directly, not via kubectl which has v2

You may still want to open an issue in kustomize though about why symlinks are followed when checking the path. 

My first instinct is that it shouldn't care if it is a symlink or an actual file, because presumably you would have had to intentionally symlinked the file yourself. But maybe there is a security issue with that too, I don't have enough background with kustomize to know the answer to that.

**Comment by brianpursley** [comment]
@hanyouqing just following up.  We discussed this issue on the the sig-cli "bug scrub" meeting today, and it was confirmed that using kustomize v3 with the `--load_restrictor` is the way to accomplish what you are asking.

/close
