### ISSUE TITLE
Support multiple endpoints for a cluster

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#908]
Since HA clusters may have multiple endpoints, it would be convenient to be able to specify multiple IP addresses in the kubeconfig and have the client pick one at random.  This would be a client-side alternative to configuring a VIP for the endpoints.

**Comment by eddiezane** [comment]
This might need to be under the main repo since we'd need to introduce a new `clusters[0].servers` array field. Would that need a KEP as well?

**Comment by soltysh** [comment]
This feature request seems like we'd be re-inventing what load balancers are meant for. There are multiple factors involved such as: balancing the load, failure detection and re-routing. All of which are nicely wrapped in LB. So having said that I don't see us implementing such a feature in the near term, unless I get convinced otherwise.
/close
