### ISSUE TITLE
Bash autocompletion hangs when additional authentication (in addition to having access credential) is required

### ISSUE THREAD

**Issue by 180254** [kubernetes/kubectl#930]
**What happened**:
I have a Azure Kuberenetes Service cluster with enabled Azure AD integration.
When you use the bash autocompletion, before you make an additional authorization, then autocompletion operation hangs.

**What you expected to happen**:
The operation does not hang.
I am asked for an additional authorization.

**How to reproduce it (as minimally and precisely as possible)**:
- Create an AKS (Azure Kubernetes Service) cluster with Azure AD enabled (https://docs.microsoft.com/en-us/azure/aks/managed-aad#create-an-aks-cluster-with-azure-ad-enabled)
- Get access credentials for a managed Kubernetes cluster. Using Azure CLI: `az aks get-credentials --name MyManagedCluster --resource-group MyResourceGroup`
- Open terminal and write `kubectl get pod `. Click TAB to get autocompletion.

The operation hangs. You cannot continue typing. The solution is to abort (Ctrl+C) or close the terminal.

**Anything else we need to know?**:
Azure Kuberenetes Service with enabled Azure AD integration requires additional authentication (in addition to having access credential). It looks as follows:
```
180254@computer:~$ kubectl get pod
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CKXXXXXXX to authenticate.
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"f862ce9a809b9832be36717bfc4efae470f59fbf", GitTreeState:"clean", BuildDate:"2020-08-24T18:41:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `Azure`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by eddiezane** [comment]
This is potentially working as expected assuming the Azure CLI is prompting for action (web auth).

@180254 if you follow the prompt to sign in with a web browser does the command return?

We may need to make sure that completion commands have a proper timeout either via or Cobra or bash.

/triage needs-information

**Comment by brianpursley** [comment]
@180254 The message says:
```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CKXXXXXXX to authenticate.
```

What happens if you open your browser and go to https://microsoft.com/devicelogin? Does that work?

**Comment by 180254** [comment]
If I do web auth beforehand, autocomplete works as expected.

If I do as in reproduction step, i.e. autocomplete is the first operation, the operation hangs _without_ any message. I expect to see message about required webauth, or the operation will timeout after some time.

**Comment by brianpursley** [comment]
I too was able to reproduce it.

Here are my steps:
```
$ az ad group create --display-name myAKSAdminGroup --mail-nickname myAKSAdminGroup
$ az ad group list --filter "displayname eq 'MyAKSAdminGroup'" -o table

DisplayName      MailEnabled    MailNickname     ObjectId                              ObjectType    Odata.type                         SecurityEnabled
---------------  -------------  ---------------  ------------------------------------  ------------  ---------------------------------  -----------------
myAKSAdminGroup  False          myAKSAdminGroup  01234567-89ab-cdef-0123-456789abcdef  Group         Microsoft.DirectoryServices.Group  True

$ az aks create -g myResourceGroup -n myManagedCluster --enable-aad --aad-admin-group-object-ids 01234567-89ab-cdef-0123-456789abcdef
$ az aks get-credentials --resource-group myResourceGroup --name myManagedCluster
$ kubectl get pod <TAB> <-- and it hangs here
```

The problem seems to be that AKS is prompting for the user to go to a website to authenticate, but the completion code is not able to show output until the command has finished running.
```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.
```

I'm not sure what fix, if any, can be made, but as I think about it, it would need to be done in one of these projects:
* **kubectl** - To complicate things, kubectl still uses Cobra's [Bash legacy dynamic completions](https://github.com/spf13/cobra/blob/master/shell_completions.md#bash-legacy-dynamic-completions).  Some work is underway to convert to the new go-based dynamic completions which I think should allow a timeout to be set.  This might be an acceptable solution, but it is dependent on the completions to be upgraded.
* **cobra** - Is there a generic way to tell cobra a timeout for completions? Even if there is, I think this will probably also be dependent on getting kubectl completions upgraded to use cobra's go-based completions as mentioned above.
* **aks** - Not sure if there is some way AKS can not try to prompt the user if kubectl is not being run interacively

not sure the best approach at this point, but I'm just putting my findings/thoughts here for later reference.

**Comment by wenpincui** [comment]
Are there any solutions to this problem?

**Comment by liptanbiswas** [comment]
@eddiezane can we reopen this? Its still an issue.
