### ISSUE TITLE
Warn about plugin name collision

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/kubectl#939]
In SIG-CLI biweekly meeting the potential for collision of the [alpha debug](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container) command and the [debug kubectl plugin](https://github.com/aylei/kubectl-debug) was brought up for when the alpha command graduates to a stable command.

We need to investigate if this will be an actual issue for plugins that become commands and decide how to handle this. The idea of detecting the collision and warning about was brought up.

/priority backlog

**Comment by eddiezane** [comment]
@ahmetb did y'all have any thoughts here?

**Comment by soltysh** [comment]
The proposal is to do something along the lines of https://github.com/kubernetes/kubernetes/pull/92343 where we're trying to warn about flags passed to plugins.

**Comment by eddiezane** [comment]
/assign @verb 

Would you be ok taking a look at this?

**Comment by ahmetb** [comment]
@eddiezane I don't have any particular opinions here. We've been rarely accepting plugins with such generic names that have the potential to be overshadowed, and giving the verbal notice that "your plugin might be silently replaced by kubectl in the future".

I have a feeling like scanning `PATH` directories for executables to discover plugins will end up being in the "hot path" of running builtin kubectl commands, and therefore will slow down all kubectl commands. If that's the case, adding such a warning is probably not worth it.

**Comment by verb** [comment]
@eddiezane Sure, I can take a look. I think we won't be able to add it in time for 1.20, however, unless we want to make it a release blocker.

@ahmetb I imagine adding new `kubectl` subcommands is pretty infrequent, so maybe we can maintain a two release window for the warning. Perhaps we could also run the check while the commands are in `kubectl alpha` to warn of upcoming collision.

**Comment by verb** [comment]
Ah, I lost track of this because it's in a different repo. We ended up performing the `kubectl alpha debug` -> `kubectl debug` rename with warnings in the release notes, so it's not relevant to this particular example. As far as I know there are no other upcoming name collisions.

I agree with wanting to avoid a path scan for every subcommand, some I'm not sure where to go with this. My only idea is to make this a feature of `kubectl alpha`, but that seems premature since `kubectl alpha` hardly ever get used. Unless anyone has any suggestions, I might "fix" this by adding comments in `alpha.go` indicating that new commands need to handle this in a one-off fashion.

/remove-lifecycle stale

**Comment by eddiezane** [comment]
This is probably safe to close. Completely agree on the path scanning and it sounds like the warnings about choosing names are documented and y'all are proactive about accepting.

Thanks for taking a look!

/close
