### ISSUE TITLE
Kubectl request forward through a proxy

### ISSUE THREAD

**Issue by kotyara85** [kubernetes/kubectl#973]
Hey there,
We aren't connection to our clusters directly, but rather through a proxy servers written in go.
We're using client-go, all requests are working fine, but with watch=true & follow=true
They're timing out and no data is being streamed back

2020/11/04 11:35:52 "GET https://localhost:8081/cluster/api/v1/namespaces/default/pods?fieldSelector=metadata.name%3Dtest-pod&resourceVersion=2957148&watch=true HTTP/2.0" from [::1]:61992 - 200 0B in 32.00589557s

The proxy is just this
```
	if r.Method == "GET" {
		res = clientset.RESTClient().Get().RequestURI(requestURI).Do(r.Context())
	} else if r.Method == "DELETE" {
		res = clientset.RESTClient().Delete().RequestURI(requestURI).Do(r.Context())
	} else if r.Method == "PATCH" {
		res = clientset.RESTClient().Patch(types.JSONPatchType).RequestURI(requestURI).Body(payload).Do(r.Context())
	} else if r.Method == "POST" {
		res = clientset.RESTClient().Post().RequestURI(requestURI).Body(payload).Do(r.Context())
	}
```

Maybe someone seen this problem?
Thanks

**Comment by eddiezane** [comment]
@kotyara85 [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernete) is a better place for this question. You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

To help kick start you there I'd imagine this is because watch requests stream data back.

Check out https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes and https://youtu.be/PLSDvFjR9HY

/close
